import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Lang = 'en' | 'es' | 'fr' | 'pt' | 'de' | 'zh' | 'ar';

interface LangStore {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const useLangStore = create<LangStore>()(
  persist(
    (set) => ({ lang: 'en', setLang: (lang) => set({ lang }) }),
    { name: 'qfs-lang' }
  )
);

const t: Record<string, Record<Lang, string>> = {
  "all.arab.name": { en: "Al Arab", es: "Al Arab", fr: "Al Arab", pt: "Al Arab", de: "Al Arab", zh: "Al Arab", ar: "Al Arab" },
  "all.arab.tag": { en: "Regional Expansion", es: "Expansión Regional", fr: "Expansion Régionale", pt: "Expansão Regional", de: "Regionale Expansion", zh: "区域扩张", ar: "التوسع الإقليمي" },
  "all.desc": { en: "QFS builds bridges of collaboration with organizations and governments for a truly global financial infrastructure.", es: "QFS construye puentes de colaboración con organizaciones y gobiernos para una infraestructura financiera verdaderamente global.", fr: "QFS construit des ponts de collaboration avec des organisations et des gouvernements pour une infrastructure financière véritablement mondiale.", pt: "QFS constrói pontes de colaboração com organizações e governos para uma infraestrutura financeira verdadeiramente global.", de: "QFS baut Kooperationsbrücken mit Organisationen und Regierungen für eine wirklich globale Finanzinfrastruktur.", zh: "QFS与组织和政府建立合作桥梁，打造真正全球化的金融基础设施。", ar: "يبني QFS جسور تعاون مع المنظمات والحكومات لبناء بنية مالية عالمية حقيقية." },
  "all.gcrm.name": { en: "GCRM Alliance", es: "Alianza GCRM", fr: "Alliance GCRM", pt: "Aliança GCRM", de: "GCRM-Allianz", zh: "GCRM联盟", ar: "تحالف GCRM" },
  "all.gcrm.tag": { en: "Strategic Partner", es: "Socio Estratégico", fr: "Partenaire Stratégique", pt: "Parceiro Estratégico", de: "Strategischer Partner", zh: "战略合作伙伴", ar: "شريك استراتيجي" },
  "all.gov.name": { en: "Government Currencies", es: "Monedas de Gobiernos", fr: "Monnaies Gouvernementales", pt: "Moedas Governamentais", de: "Regierungswährungen", zh: "政府货币", ar: "العملات الحكومية" },
  "all.gov.tag": { en: "Digital Government", es: "Gobierno Digital", fr: "Gouvernement Numérique", pt: "Governo Digital", de: "Digitale Regierung", zh: "数字政府", ar: "الحكومة الرقمية" },
  "all.nesg.name": { en: "NESG", es: "NESG", fr: "NESG", pt: "NESG", de: "NESG", zh: "NESG", ar: "NESG" },
  "all.nesg.tag": { en: "NESG Ecosystem", es: "Ecosistema NESG", fr: "Écosystème NESG", pt: "Ecossistema NESG", de: "NESG-Ökosystem", zh: "NESG生态系统", ar: "نظام NESG" },
  "all.subtitle": { en: "Strategic Alliances", es: "Alianzas Estratégicas", fr: "Alliances Stratégiques", pt: "Alianças Estratégicas", de: "Strategische Allianzen", zh: "战略联盟", ar: "التحالفات الاستراتيجية" },
  "all.title": { en: "Alliances", es: "Alianzas", fr: "Alliances", pt: "Alianças", de: "Allianzen", zh: "联盟", ar: "التحالفات" },
  "all.title2": { en: "Global", es: "Globales", fr: "Mondiales", pt: "Globais", de: "Global", zh: "全球", ar: "العالمية" },
  "cta.desc": { en: "QFS is more than a wallet, more than payments, more than an exchange. It is an integrated digital financial ecosystem designed for the next generation of the global economy.", es: "QFS es más que una wallet, más que pagos, más que un exchange. Es un ecosistema financiero digital integrado diseñado para la próxima generación de la economía global.", fr: "QFS est plus qu'un portefeuille, plus que des paiements, plus qu'un exchange. C'est un écosystème financier numérique intégré conçu pour la prochaine génération de l'économie mondiale.", pt: "QFS é mais que uma carteira, mais que pagamentos, mais que uma exchange. É um ecossistema financeiro digital integrado projetado para a próxima geração da economia global.", de: "QFS ist mehr als eine Wallet, mehr als Zahlungen, mehr als eine Börse. Es ist ein integriertes digitales Finanzökosystem für die nächste Generation der Weltwirtschaft.", zh: "QFS不仅仅是钱包、支付或交易所。它是一个为全球经济下一代设计的集成数字金融生态系统。", ar: "QFS ليس مجرد محفظة أو دفع أو بورصة. إنه نظام مالي رقمي متكامل مصمم للجيل القادم من الاقتصاد العالمي." },
  "cta.title1": { en: "Building the Future", es: "Construyendo el Futuro", fr: "Construire l'Avenir", pt: "Construindo o Futuro", de: "Die Zukunft aufbauen", zh: "构建未来", ar: "بناء المستقبل" },
  "cta.title2": { en: "of Digital Finance", es: "de las Finanzas Digitales", fr: "des Finances Numériques", pt: "das Finanças Digitais", de: "der Digitalen Finanzen", zh: "数字金融的未来", ar: "للمال الرقمي" },
  "eco.desc": { en: "Modular financial architecture integrating different services within a single digital ecosystem.", es: "Arquitectura financiera modular que integra diferentes servicios dentro de un mismo ecosistema digital.", fr: "Architecture financière modulaire intégrant différents services au sein d'un seul écosystème numérique.", pt: "Arquitetura financeira modular que integra diferentes serviços dentro de um único ecossistema digital.", de: "Modulare Finanzarchitektur, die verschiedene Dienste in einem einzigen digitalen Ökosystem integriert.", zh: "模块化金融架构，在单一数字生态系统中整合不同服务。", ar: "هيكل مالي موديولار يدمج خدمات مختلفة ضمن نظام رقمي متكامل." },
  "eco.subtitle": { en: "The Ecosystem", es: "El Ecosistema", fr: "L'Écosystème", pt: "O Ecossistema", de: "Das Ökosystem", zh: "生态系统", ar: "النظام البيئي" },
  "faq.subtitle": { en: "FAQ", es: "Preguntas Frecuentes", fr: "FAQ", pt: "Perguntas Frequentes", de: "FAQ", zh: "常见问题", ar: "الأسئلة الشائعة" },
  "foot.alliances": { en: "Alliances", es: "Alianzas", fr: "Alliances", pt: "Alianças", de: "Allianzen", zh: "联盟", ar: "التحالفات" },
  "foot.copyright.prefix": { en: "QFS Official", es: "QFS Official", fr: "QFS Official", pt: "QFS Official", de: "QFS Official", zh: "QFS Official", ar: "QFS Official" },
  "foot.copyright.suffix": { en: "Quantum Financial System.", es: "Sistema Financiero Cuántico.", fr: "Système Financier Quantique.", pt: "Sistema Financeiro Quântico.", de: "Quanten-Finanzsystem.", zh: "量子金融系统。", ar: "نظام المال الكمي." },
  "foot.desc": { en: "The Next Generation of Digital Finance. Technology, Security, Decentralization, Innovation.", es: "La próxima generación de las finanzas digitales. Tecnología, Seguridad, Descentralización, Innovación.", fr: "La prochaine génération de la finance numérique. Technologie, Sécurité, Décentralisation, Innovation.", pt: "A próxima geração das finanças digitais. Tecnologia, Segurança, Descentralização, Inovação.", de: "Die nächste Generation der digitalen Finanzen. Technologie, Sicherheit, Dezentralisierung, Innovation.", zh: "数字金融的下一代。技术、安全、去中心化、创新。", ar: "الجيل القادم من المال الرقمي. التكنولوجيا، الأمان، اللامركزية، الابتكار." },
  "foot.products": { en: "Products", es: "Productos", fr: "Produits", pt: "Produtos", de: "Produkte", zh: "产品", ar: "المنتجات" },
  "foot.resources": { en: "Resources", es: "Recursos", fr: "Ressources", pt: "Recursos", de: "Ressourcen", zh: "资源", ar: "الموارد" },
  "foot.tag.connectivity": { en: "Global Connectivity", es: "Conectividad Global", fr: "Connectivité Mondiale", pt: "Conectividade Global", de: "Globale Vernetzung", zh: "全球连接", ar: "الاتصال العالمي" },
  "foot.tag.decentralization": { en: "Decentralization", es: "Descentralización", fr: "Décentralisation", pt: "Descentralização", de: "Dezentralisierung", zh: "去中心化", ar: "اللامركزية" },
  "foot.tag.finance": { en: "Digital Finance", es: "Finanzas Digitales", fr: "Finances Numériques", pt: "Finanças Digitais", de: "Digitale Finanzen", zh: "数字金融", ar: "المال الرقمي" },
  "foot.tag.innovation": { en: "Innovation", es: "Innovación", fr: "Innovation", pt: "Inovação", de: "Innovation", zh: "创新", ar: "الابتكار" },
  "foot.tag.security": { en: "Security", es: "Seguridad", fr: "Sécurité", pt: "Segurança", de: "Sicherheit", zh: "安全", ar: "الأمان" },
  "foot.tag.technology": { en: "Technology", es: "Tecnología", fr: "Technologie", pt: "Tecnologia", de: "Technologie", zh: "技术", ar: "التكنولوجيا" },
  "hero.badge": { en: "QUANTUM FINANCIAL SYSTEM", es: "SISTEMA FINANCIERO CUÁNTICO", fr: "SYSTÈME FINANCIER QUANTIQUE", pt: "SISTEMA FINANCEIRO QUÂNTICO", de: "QUANTEN-FINANZSYSTEM", zh: "量子金融系统", ar: "نظام المال الكمي" },
  "hero.desc": { en: "QFS Official develops a new digital financial infrastructure integrating blockchain, artificial intelligence, advanced cryptographic security, digital payments and decentralized financial services.", es: "QFS Official desarrolla una nueva infraestructura financiera digital que integra blockchain, inteligencia artificial, seguridad criptográfica avanzada, pagos digitales y servicios financieros descentralizados.", fr: "QFS Official développe une nouvelle infrastructure financière numérique intégrant la blockchain, l'intelligence artificielle, la sécurité cryptographique avancée, les paiements numériques et les services financiers décentralisés.", pt: "QFS Official desenvolve uma nova infraestrutura financeira digital integrando blockchain, inteligência artificial, segurança criptográfica avançada, pagamentos digitais e serviços financeiros descentralizados.", de: "QFS Official entwickelt eine neue digitale Finanzinfrastruktur, die Blockchain, Künstliche Intelligenz, fortschrittliche Kryptografie, digitale Zahlungen und dezentrale Finanzdienstleistungen integriert.", zh: "QFS Official 开发了一套新的数字金融基础设施，整合区块链、人工智能、高级加密安全、数字支付和去中心化金融服务。", ar: "تطور QFS Official بنية مالية رقمية جديدة تدمج البلوكتشين والذكاء الاصطناعي والأمن التشفيري المتقدم والدفع الرقمي والخدمات المالية اللامركزية." },
  "hero.explore_btn": { en: "Explore QFS", es: "Explorar QFS", fr: "Explorer QFS", pt: "Explorar QFS", de: "QFS entdecken", zh: "探索 QFS", ar: "استكشاف QFS" },
  "hero.qfspay": { en: "QFSPay", es: "QFSPay", fr: "QFSPay", pt: "QFSPay", de: "QFSPay", zh: "QFSPay", ar: "QFSPay" },
  "hero.tags.connectivity": { en: "Global Connectivity", es: "Conectividad Global", fr: "Connectivité Mondiale", pt: "Conectividade Global", de: "Globale Vernetzung", zh: "全球连接", ar: "الاتصال العالمي" },
  "hero.tags.decentralization": { en: "Decentralization", es: "Descentralización", fr: "Décentralisation", pt: "Descentralização", de: "Dezentralisierung", zh: "去中心化", ar: "اللامركزية" },
  "hero.tags.finance": { en: "Digital Finance", es: "Finanzas Digitales", fr: "Finances Numériques", pt: "Finanças Digitais", de: "Digitale Finanzen", zh: "数字金融", ar: "المال الرقمي" },
  "hero.tags.security": { en: "Security", es: "Seguridad", fr: "Sécurité", pt: "Segurança", de: "Sicherheit", zh: "安全", ar: "الأمان" },
  "hero.tags.technology": { en: "Technology", es: "Tecnología", fr: "Technologie", pt: "Tecnologia", de: "Technologie", zh: "技术", ar: "التكنولوجيا" },
  "hero.title1": { en: "The Future of", es: "El Futuro de las", fr: "L'Avenir des", pt: "O Futuro das", de: "Die Zukunft der", zh: "数字金融的未来", ar: "مستقبل" },
  "hero.title2": { en: "Digital Finance", es: "Finanzas Digitales", fr: "Finances Numériques", pt: "Finanças Digitais", de: "Digitalen Finanzen", zh: "数字金融的未来", ar: "المال الرقمي" },
  "hero.wallet": { en: "QFS Wallet", es: "QFS Wallet", fr: "QFS Wallet", pt: "QFS Wallet", de: "QFS Wallet", zh: "QFS Wallet", ar: "QFS Wallet" },
  "lang.ar": { en: "العربية", es: "Árabe", fr: "Arabe", pt: "Árabe", de: "Arabisch", zh: "阿拉伯语", ar: "العربية" },
  "lang.de": { en: "Deutsch", es: "Alemán", fr: "Allemand", pt: "Alemão", de: "Deutsch", zh: "德语", ar: "الألمانية" },
  "lang.en": { en: "English", es: "Inglés", fr: "Anglais", pt: "Inglês", de: "Englisch", zh: "英语", ar: "الإنجليزية" },
  "lang.es": { en: "Español", es: "Español", fr: "Espagnol", pt: "Espanhol", de: "Spanisch", zh: "西班牙语", ar: "الإسبانية" },
  "lang.fr": { en: "Français", es: "Francés", fr: "Français", pt: "Francês", de: "Französisch", zh: "法语", ar: "الفرنسية" },
  "lang.pt": { en: "Português", es: "Portugués", fr: "Portugais", pt: "Português", de: "Portugiesisch", zh: "葡萄牙语", ar: "البرتغالية" },
  "lang.zh": { en: "中文", es: "Chino", fr: "Chinois", pt: "Chinês", de: "Chinesisch", zh: "中文", ar: "الصينية" },
  "nav.explore": { en: "Explore QFS", es: "Explorar QFS", fr: "Explorer QFS", pt: "Explorar QFS", de: "QFS entdecken", zh: "探索 QFS", ar: "استكشاف QFS" },
  "nav.home": { en: "Home", es: "Inicio", fr: "Accueil", pt: "Inicio", de: "Startseite", zh: "首页", ar: "الرئيسية" },
  "nav.join": { en: "Join Community", es: "Unirse a la Comunidad", fr: "Rejoindre la Communauté", pt: "Junte-se à Comunidade", de: "Gemeinschaft beitreten", zh: "加入社区", ar: "انضم إلى المجتمع" },
  "nav.portal": { en: "Portal", es: "Portal", fr: "Portail", pt: "Portal", de: "Portal", zh: "门户", ar: "البوابة" },
  "nav.roadmap": { en: "Roadmap", es: "Roadmap", fr: "Feuille de Route", pt: "Roteiro", de: "Roadmap", zh: "路线图", ar: "خريطة الطريق" },
  "nav.whitepaper": { en: "White Paper", es: "Libro Blanco", fr: "Livre Blanc", pt: "Livro Branco", de: "Whitepaper", zh: "白皮书", ar: "الوثيقة التفصيلية" },
  "pil.desc": { en: "QFS proposes a new financial architecture based on principles that will transform the digital economy.", es: "QFS propone una nueva arquitectura financiera basada en principios que transformarán la economía digital.", fr: "QFS propose une nouvelle architecture financière basée sur des principes qui transformeront l'économie numérique.", pt: "QFS propõe uma nova arquitetura financeira baseada em princípios que transformarão a economia digital.", de: "QFS schlägt eine neue Finanzarchitektur vor, die auf Prinzipien basiert, die die digitale Wirtschaft transformieren werden.", zh: "QFS 提出了一种基于将改变数字经济的原则的新金融架构。", ar: "يقترح QFS هيكلاً مالياً جديداً قائماً على مبادئ ستحول الاقتصاد الرقمي." },
  "pil.subtitle": { en: "Architecture", es: "Arquitectura", fr: "Architecture", pt: "Arquitetura", de: "Architektur", zh: "架构", ar: "الهيكل المعماري" },
  "pil.title1": { en: "Five", es: "Cinco", fr: "Cinq", pt: "Cinco", de: "Fünf", zh: "五大", ar: "خمسة" },
  "pil.title2": { en: "Pillars", es: "Pilares", fr: "Piliers", pt: "Pilares", de: "Säulen", zh: "支柱", ar: "ركائز" },
  "pil.title3": { en: "Fundamental", es: "Fundamentales", fr: "Fondamentaux", pt: "Fundamentais", de: "Grundlegend", zh: "基础", ar: "أساسية" },
  "portal.badge": { en: "PORTAL", es: "PORTAL", fr: "PORTAIL", pt: "PORTAL", de: "PORTAL", zh: "门户", ar: "البوابة" },
  "portal.card.desc": { en: "Your QFS digital assets available for everyday purchases through the QFSPay card.", es: "Tus activos digitales QFS disponibles para compras cotidianas a través de la tarjeta QFSPay.", fr: "Vos actifs numériques QFS disponibles pour les achats quotidiens via la carte QFSPay.", pt: "Seus ativos digitais QFS disponíveis para compras diárias através do cartão QFSPay.", de: "Ihre QFS-digitalen Assets für tägliche Einkäufe verfügbar über die QFSPay-Karte.", zh: "您的QFS数字资产可通过QFSPay卡用于日常购买。", ar: "أصولك الرقمية QFS متاحة للمشتريات اليومية عبر بطاقة QFSPay." },
  "portal.card.title": { en: "QFSPay Card", es: "Tarjeta QFSPay", fr: "Carte QFSPay", pt: "Cartão QFSPay", de: "QFSPay Karte", zh: "QFSPay 卡", ar: "بطاقة QFSPay" },
  "portal.currencies": { en: "Supported Currencies", es: "Monedas Soportadas", fr: "Devises Prises en Charge", pt: "Moedas Suportadas", de: "Unterstützte Währungen", zh: "支持的货币", ar: "العملات المدعومة" },
  "portal.desc": { en: "Explore the currencies, features and services available within the QFS ecosystem.", es: "Explore las monedas, funciones y servicios disponibles dentro del ecosistema QFS.", fr: "Explorez les devises, fonctionnalités et services disponibles dans l'écosystème QFS.", pt: "Explore as moedas, recursos e serviços disponíveis no ecossistema QFS.", de: "Erkunden Sie die Währungen, Funktionen und Dienste im QFS-Ökosystem.", zh: "探索QFS生态系统中可用的货币、功能和服务。", ar: "استكشف العملات والميزات والخدمات المتاحة في نظام QFS." },
  "portal.features": { en: "Platform Features", es: "Características de la Plataforma", fr: "Fonctionnalités de la Plateforme", pt: "Recursos da Plataforma", de: "Plattform-Funktionen", zh: "平台功能", ar: "ميزات المنصة" },
  "portal.subtitle": { en: "Digital Financial Gateway", es: "Puerta de Acceso Financiera Digital", fr: "Passerelle Financière Numérique", pt: "Portal Financeiro Digital", de: "Digitales Finanzportal", zh: "数字金融网关", ar: "البوابة المالية الرقمية" },
  "portal.title": { en: "QFS Portal", es: "Portal QFS", fr: "Portail QFS", pt: "Portal QFS", de: "QFS Portal", zh: "QFS 门户", ar: "بوابة QFS" },
  "prod.ai.subtitle": { en: "Intelligent Finance", es: "Finanzas Inteligentes", fr: "Finance Intelligente", pt: "Finanças Inteligentes", de: "Intelligente Finanzen", zh: "智能金融", ar: "المال الذكي" },
  "prod.ai.title": { en: "QFS + AI", es: "QFS + IA", fr: "QFS + IA", pt: "QFS + IA", de: "QFS + KI", zh: "QFS + AI", ar: "QFS + AI" },
  "prod.cards.desc": { en: "Connects the QFS digital ecosystem with real-world physical and digital payment solutions.", es: "Conecta el ecosistema digital QFS con soluciones de pago físicas y digitales del mundo real.", fr: "Connecte l'écosystème numérique QFS avec des solutions de paiement physiques et numériques du monde réel.", pt: "Conecta o ecossistema digital QFS com soluções de pagamento físicas e digitais do mundo real.", de: "Verbindet das QFS-digitale Ökosystem mit physischen und digitalen Zahlungslösungen der realen Welt.", zh: "将QFS数字生态系统与现实世界的实体和数字支付解决方案连接起来。", ar: "يربط نظام QFS الرقمي بحلول الدفع الفيزيائية والرقمية في العالم الحقيقي." },
  "prod.cards.subtitle": { en: "Digital-to-Physical", es: "Digital a Físico", fr: "Numérique vers Physique", pt: "Digital para Físico", de: "Digital-zu-Physisch", zh: "数字到实体", ar: "رقمي إلى فيزيائي" },
  "prod.cards.title": { en: "QFS Quantum Cards", es: "QFS Quantum Cards", fr: "QFS Quantum Cards", pt: "QFS Quantum Cards", de: "QFS Quantum Cards", zh: "QFS Quantum Cards", ar: "QFS Quantum Cards" },
  "prod.dex.desc": { en: "Decentralized platform for exchanging digital assets with access to ecosystem markets and liquidity.", es: "Plataforma descentralizada para el intercambio de activos digitales con acceso a mercados y liquidez del ecosistema.", fr: "Plateforme décentralisée pour l'échange d'actifs numériques avec accès aux marchés et à la liquidité de l'écosystème.", pt: "Plataforma descentralizada para troca de ativos digitais com acesso a mercados e liquidez do ecossistema.", de: "Dezentrale Plattform zum Austausch digitaler Assets mit Zugang zu Ökosystem-Märkten und Liquidität.", zh: "去中心化的数字资产交易平台，可访问生态系统市场和流动性。", ar: "منصة لامركزية لتبادل الأصول الرقمية مع الوصول إلى أسواق وسيولة النظام." },
  "prod.dex.subtitle": { en: "Decentralized Trading", es: "Trading Descentralizado", fr: "Trading Décentralisé", pt: "Trading Descentralizado", de: "Dezentraler Handel", zh: "去中心化交易", ar: "التداول اللامركزي" },
  "prod.dex.title": { en: "QFS Exchange DEX", es: "QFS Exchange DEX", fr: "QFS Exchange DEX", pt: "QFS Exchange DEX", de: "QFS Exchange DEX", zh: "QFS Exchange DEX", ar: "QFS Exchange DEX" },
  "prod.qfspay.desc": { en: "Digital payments for a connected economy. Facilitates the use of digital assets for everyday and commercial operations.", es: "Pagos digitales para una economía conectada. Facilita la utilización de activos digitales para operaciones cotidianas y comerciales.", fr: "Paiements numériques pour une économie connectée. Facilite l'utilisation d'actifs numériques pour les opérations quotidiennes et commerciales.", pt: "Pagamentos digitais para uma economia conectada. Facilita o uso de ativos digitais para operações diárias e comerciais.", de: "Digitale Zahlungen für eine vernetzte Wirtschaft. Erleichtert die Nutzung digitaler Assets für alltägliche und kommerzielle Operationen.", zh: "为互联经济提供数字支付。促进数字资产在日常和商业运营中的使用。", ar: "دفع رقمي لاقتصاد متصل. يسهل استخدام الأصول الرقمية للعمليات اليومية والتجارية." },
  "prod.qfspay.subtitle": { en: "Digital Payments", es: "Pagos Digitales", fr: "Paiements Numériques", pt: "Pagamentos Digitais", de: "Digitale Zahlungen", zh: "数字支付", ar: "الدفع الرقمي" },
  "prod.qfspay.title": { en: "QFSPay", es: "QFSPay", fr: "QFSPay", pt: "QFSPay", de: "QFSPay", zh: "QFSPay", ar: "QFSPay" },
  "prod.subtitle": { en: "Products", es: "Productos", fr: "Produits", pt: "Produtos", de: "Produkte", zh: "产品", ar: "المنتجات" },
  "prod.wallet.balance": { en: "Total Balance", es: "Balance Total", fr: "Solde Total", pt: "Saldo Total", de: "Gesamtguthaben", zh: "总余额", ar: "الرصيد الإجمالي" },
  "prod.wallet.desc": { en: "The user's entry point to the QFS ecosystem. Manage different types of digital assets from a single interface with advanced security.", es: "El punto de acceso del usuario al ecosistema QFS. Gestione diferentes tipos de activos digitales desde una única interfaz con seguridad avanzada.", fr: "Le point d'accès des utilisateurs à l'écosystème QFS. Gérez différents types d'actifs numériques depuis une seule interface avec une sécurité avancée.", pt: "O ponto de acesso do usuário ao ecossistema QFS. Gerencie diferentes tipos de ativos digitais de uma única interface com segurança avançada.", de: "Der Zugangspunkt der Benutzer zum QFS-Ökosystem. Verwalten Sie verschiedene digitale Asset-Typen von einer einzigen Oberfläche mit fortschrittlicher Sicherheit.", zh: "用户进入QFS生态系统的入口。通过具有高级安全性的单一界面管理各种数字资产。", ar: "نقطة دخول المستخدم إلى نظام QFS. إدارة أنواع مختلفة من الأصول الرقمية من واجهة واحدة بأمان متقدم." },
  "prod.wallet.month": { en: "this month", es: "este mes", fr: "ce mois", pt: "este mês", de: "diesen Monat", zh: "本月", ar: "هذا الشهر" },
  "prod.wallet.subtitle": { en: "Your Digital Financial Hub", es: "Tu Centro Financiero Digital", fr: "Votre Hub Financier Numérique", pt: "Seu Hub Financeiro Digital", de: "Ihr Digitales Finanzzentrum", zh: "您的数字金融中心", ar: "مركزك المالي الرقمي" },
  "prod.wallet.title": { en: "QFS Wallet", es: "QFS Wallet", fr: "QFS Wallet", pt: "QFS Wallet", de: "QFS Wallet", zh: "QFS Wallet", ar: "QFS Wallet" },
  "road.badge": { en: "ROADMAP", es: "ROADMAP", fr: "FEUILLE DE ROUTE", pt: "ROTEIRO", de: "ROADMAP", zh: "路线图", ar: "خريطة الطريق" },
  "road.desc": { en: "Progressive development of the QFS ecosystem through strategic phases, from the base infrastructure to global digital finance.", es: "Desarrollo progresivo del ecosistema QFS a través de fases estratégicas, desde la infraestructura base hasta las finanzas digitales globales.", fr: "Développement progressif de l'écosystème QFS à travers des phases stratégiques, de l'infrastructure de base à la finance numérique mondiale.", pt: "Desenvolvimento progressivo do ecossistema QFS através de fases estratégicas, da infraestrutura bás às finanças digitais globais.", de: "Progressive Entwicklung des QFS-Ökosystems durch strategische Phasen, von der Basisinfrastruktur bis zur globalen digitalen Finanzierung.", zh: "通过战略阶段逐步开发QFS生态系统，从基础设施到全球数字金融。", ar: "التطوير التدريجي لنظام QFS عبر مراحل استراتيجية، من البنية الأساسية إلى المال الرقمي العالمي." },
  "road.eco.desc": { en: "An interconnected suite of financial services powered by quantum technology.", es: "Una suite interconectada de servicios financieros impulsada por tecnología cuántica.", fr: "Une suite interconnectée de services financiers alimentée par la technologie quantique.", pt: "Um conjunto interconectado de serviços financeiros impulsionado por tecnologia quântica.", de: "Eine verbundene Suite von Finanzdienstleistungen, angetrieben von Quantentechnologie.", zh: "由量子技术驱动的互联金融服务套件。", ar: "مجموعة مترابطة من الخدمات المالية مدعومة بتكنولوجيا الكم." },
  "road.eco.dev": { en: "In Development", es: "En Desarrollo", fr: "En Développement", pt: "Em Desenvolvimento", de: "In Entwicklung", zh: "开发中", ar: "قيد التطوير" },
  "road.eco.live": { en: "Live", es: "Activo", fr: "Actif", pt: "Ativo", de: "Aktiv", zh: "已上线", ar: "نشط" },
  "road.eco.soon": { en: "Coming Soon", es: "Próximamente", fr: "Prochainement", pt: "Em Breve", de: "Demnächst", zh: "即将推出", ar: "قريباً" },
  "road.eco.subtitle": { en: "Ecosystem Map", es: "Mapa del Ecosistema", fr: "Carte de l'Écosystème", pt: "Mapa do Ecossistema", de: "Ökosystem-Karte", zh: "生态系统图", ar: "خريطة النظام" },
  "road.phases": { en: "Development Phases", es: "Fases de Desarrollo", fr: "Phases de Développement", pt: "Fases de Desenvolvimento", de: "Entwicklungsphasen", zh: "开发阶段", ar: "مراحل التطوير" },
  "road.timeline": { en: "Timeline", es: "Línea de Tiempo", fr: "Chronologie", pt: "Linha do Tempo", de: "Zeitstrahl", zh: "时间线", ar: "الجدول الزمني" },
  "road.title": { en: "QFS Roadmap", es: "Roadmap QFS", fr: "Feuille de Route QFS", pt: "Roteiro QFS", de: "QFS Roadmap", zh: "QFS 路线图", ar: "خريطة طريق QFS" },
  "sec.desc": { en: "Security is one of the fundamental pillars of the QFS ecosystem. Designed to evolve alongside new digital threats through a multi-layered security architecture.", es: "La seguridad constituye uno de los pilares fundamentales del ecosistema QFS. Diseñado para evolucionar con las nuevas amenazas digitales mediante una arquitectura de seguridad multicapa.", fr: "La sécurité est l'un des piliers fondamentaux de l'écosystème QFS. Conçu pour évoluer avec les nouvelles menaces numériques grâce à une architecture de sécurité multicouche.", pt: "A segurança é um dos pilares fundamentais do ecossistema QFS. Projetado para evoluir junto com as novas ameaças digitais por meio de uma arquitetura de segurança multicamadas.", de: "Sicherheit ist einer der Grundpfeiler des QFS-Ökosystems. Konzipiert, um sich mit neuen digitalen Bedrohungen durch eine mehrschichtige Sicherheitsarchitektur weiterzuentwickeln.", zh: "安全是QFS生态系统的基本支柱之一。通过多层安全架构设计，能够随新型数字威胁一起演进。", ar: "الأمان هو أحد الركائز الأساسية لنظام QFS. مصمم للتطور مع التهديدات الرقمية الجديدة من خلال هيكل أماني متعدد الطبقات." },
  "sec.subtitle": { en: "Security", es: "Seguridad", fr: "Sécurité", pt: "Segurança", de: "Sicherheit", zh: "安全", ar: "الأمان" },
  "sec.title": { en: "QFS Security", es: "Seguridad QFS", fr: "Sécurité QFS", pt: "Segurança QFS", de: "QFS Sicherheit", zh: "QFS 安全", ar: "أمان QFS" },
  "why.access": { en: "Access", es: "Acceso", fr: "Accès", pt: "Acesso", de: "Zugang", zh: "接入", ar: "الوصول" },
  "why.access.desc": { en: "Financial services accessible from an integrated platform.", es: "Servicios financieros accesibles desde una plataforma integrada.", fr: "Services financiers accessibles depuis une plateforme intégrée.", pt: "Serviços financeiros acessíveis de uma plataforma integrada.", de: "Finanzdienstleistungen zugänglich über eine integrierte Plattform.", zh: "通过集成平台即可访问的金融服务。", ar: "خدمات مالية متاحة من منصة متكاملة." },
  "why.innovation": { en: "Innovation", es: "Innovación", fr: "Innovation", pt: "Inovação", de: "Innovation", zh: "创新", ar: "الابتكار" },
  "why.innovation.desc": { en: "Blockchain + AI + Cryptography + Digital Finance.", es: "Blockchain + IA + Criptografía + Finanzas Digitales.", fr: "Blockchain + IA + Cryptographie + Finances Numériques.", pt: "Blockchain + IA + Criptografia + Finanças Digitais.", de: "Blockchain + KI + Kryptografie + Digitale Finanzen.", zh: "区块链 + AI + 加密术 + 数字金融。", ar: "البلوكتشين + الذكاء الاصطناعي + التشفير + المال الرقمي." },
  "why.interop": { en: "Interoperability", es: "Interoperabilidad", fr: "Interopérabilité", pt: "Interoperabilidade", de: "Interoperabilität", zh: "互操作性", ar: "التشابكية" },
  "why.interop.desc": { en: "Connection between different networks and assets.", es: "Conexión entre diferentes redes y activos.", fr: "Connexion entre différents réseaux et actifs.", pt: "Conexão entre diferentes redes e ativos.", de: "Verbindung zwischen verschiedenen Netzwerken und Assets.", zh: "不同网络和资产之间的连接。", ar: "الترابط بين الشبكات والأصول المختلفة." },
  "why.security": { en: "Security", es: "Seguridad", fr: "Sécurité", pt: "Segurança", de: "Sicherheit", zh: "安全", ar: "الأمان" },
  "why.security.desc": { en: "Infrastructure designed with security as absolute priority.", es: "Infraestructura diseñada con seguridad como prioridad absoluta.", fr: "Infrastructure conçue avec la sécurité comme priorité absolue.", pt: "Infraestrutura projetada com segurança como prioridade absoluta.", de: "Infrastruktur mit Sicherheit als absolutem Priorität.", zh: "以安全为绝对优先事项设计的基础设施。", ar: "بنية تحتيا الأمان كأولوية مطلقة." },
  "why.speed": { en: "Speed", es: "Velocidad", fr: "Vitesse", pt: "Velocidade", de: "Geschwindigkeit", zh: "速度", ar: "السرعة" },
  "why.speed.desc": { en: "Efficient and scalable digital processing.", es: "Procesamiento digital eficiente y escalable.", fr: "Traitement numérique efficace et évolutif.", pt: "Processamento digital eficiente e escalável.", de: "Effiziente und skalierbare digitale Verarbeitung.", zh: "高效可扩展的数字处理。", ar: "معالجة رقمية فعالة وقابلة للتوسع." },
  "why.subtitle": { en: "Why QFS", es: "Por qué QFS", fr: "Pourquoi QFS", pt: "Por que QFS", de: "Warum QFS", zh: "为什么选QFS", ar: "لماذا QFS" },
  "why.title": { en: "Why QFS?", es: "¿Por qué QFS?", fr: "Pourquoi QFS ?", pt: "Por que QFS?", de: "Warum QFS?", zh: "为什么选QFS？", ar: "لماذا QFS؟" },
  "why.transparency": { en: "Transparency", es: "Transparencia", fr: "Transparence", pt: "Transparência", de: "Transparenz", zh: "透明度", ar: "الشفافية" },
  "why.transparency.desc": { en: "Blockchain technology and verifiable records.", es: "Tecnología blockchain y registros verificables.", fr: "Technologie blockchain et registres vérifiables.", pt: "Tecnologia blockchain e registros verificáveis.", de: "Blockchain-Technologie und überprüfbare Aufzeichnungen.", zh: "区块链技术和可验证记录。", ar: "تكنولوجيا البلوكتشين وسجلات قابلة للتحقق." },
  "wp.badge": { en: "WHITE PAPER", es: "LIBRO BLANCO", fr: "LIVRE BLANC", pt: "LIVRO BRANCO", de: "WHITEPAPER", zh: "白皮书", ar: "الوثيقة التفصيلية" },
  "wp.confidential": { en: "Confidential", es: "Confidencial", fr: "Confidentiel", pt: "Confidencial", de: "Vertraulich", zh: "机密", ar: "سري" },
  "wp.desc": { en: "Technical document describing the vision, architecture and progressive development of the Quantum Financial System.", es: "Documento técnico que describe la visión, arquitectura y desarrollo progresivo del Sistema Financiero Cuántico.", fr: "Document technique décrivant la vision, l'architecture et le développement progressif du Système Financier Quantique.", pt: "Documento técnico que descreve a visão, arquitetura e desenvolvimento progressivo do Sistema Financeiro Quântico.", de: "Technisches Dokument beschreiben Vision, Architektur und progressive Entwicklung des Quanten-Finanzsystems.", zh: "描述量子金融系统的愿景、架构和逐步开发的技术文档。", ar: "وثيقة تقنية تصف رؤية وهيكل والتطوير التدريجي للنظام المالي الكمي." },
  "wp.sec01": { en: "Executive Summary", es: "Resumen Ejecutivo", fr: "Résumé Exécutif", pt: "Resumo Executivo", de: "Zusammenfassung", zh: "执行摘要", ar: "الملخص التنفيذي" },
  "wp.sec02": { en: "Vision & Architecture", es: "Visión y Arquitectura", fr: "Vision et Architecture", pt: "Visão e Arquitetura", de: "Vision und Architektur", zh: "愿景与架构", ar: "الرؤية والهيكل" },
  "wp.sec03": { en: "Ecosystem Components", es: "Componentes del Ecosistema", fr: "Composants de l'Écosystème", pt: "Componentes do Ecossistema", de: "Ökosystem-Komponenten", zh: "生态系统组件", ar: "مكونات النظام" },
  "wp.sec04": { en: "Security & Cryptography", es: "Seguridad y Criptografía", fr: "Sécurité et Cryptographie", pt: "Segurança e Criptografia", de: "Sicherheit und Kryptografie", zh: "安全与加密术", ar: "الأمان والتشفير" },
  "wp.sec05": { en: "Multichain Infrastructure", es: "Infraestructura Multicadena", fr: "Infrastructure Multichaîne", pt: "Infraestrutura Multichain", de: "Multichain-Infrastruktur", zh: "多链基础设施", ar: "بنية تحتية متعددة السلسلة" },
  "wp.sec06": { en: "Artificial Intelligence", es: "Inteligencia Artificial", fr: "Intelligence Artificielle", pt: "Inteligência Artificial", de: "Künstliche Intelligenz", zh: "人工智能", ar: "الذكاء الاصطناعي" },
  "wp.sec07": { en: "Digital Asset Economy", es: "Economía de Activos Digitales", fr: "Économie des Actifs Numériques", pt: "Economia de Ativos Digitais", de: "Digitale Asset-Wirtschaft", zh: "数字资产经济", ar: "اقتصاد الأصول الرقمية" },
  "wp.sec08": { en: "Institutional Solutions", es: "Soluciones Institucionales", fr: "Solutions Institutionnelles", pt: "Soluções Institucionais", de: "Institutionelle Lösungen", zh: "机构解决方案", ar: "حلول مؤسسية" },
  "wp.sec09": { en: "Strategic Alliances", es: "Alianzas Estratégicas", fr: "Alliances Stratégiques", pt: "Alianças Estratégicas", de: "Strategische Allianzen", zh: "战略联盟", ar: "التحالفات الاستراتيجية" },
  "wp.sec10": { en: "NESG Community", es: "Comunidad NESG", fr: "Communauté NESG", pt: "Comunidade NESG", de: "NESG-Community", zh: "NESG社区", ar: "مجتمع NESG" },
  "wp.title": { en: "QFS White Paper", es: "Libro Blanco QFS", fr: "Livre Blanc QFS", pt: "Livro Branco QFS", de: "QFS Whitepaper", zh: "QFS 白皮书", ar: "الوثيقة التفصيلية QFS" },
  "wp.toc": { en: "Contents", es: "Contenido", fr: "Contenu", pt: "Conteúdo", de: "Inhalt", zh: "目录", ar: "المحتويات" },
};

const td: Record<string, Record<Lang, string[]>> = {
  "ai.items": {
    en: ["AI Security", "Anomalous transaction detection", "AI Risk Monitoring", "Risk and pattern analysis", "AI Financial Assistance", "Smart tools for users", "AI Compliance", "Compliance automation"],
    es: ["IA Seguridad", "Detección de transacciones anómalas", "IA Monitoreo de Riesgos", "Análisis de riesgos y patrones", "IA Asistencia Financiera", "Herramientas inteligentes", "IA Cumplimiento", "Automatización de cumplimiento"],
    fr: ["IA Sécurité", "Détection de transactions anormales", "IA Surveillance des Risques", "Analyse des risques et patterns", "IA Assistance Financière", "Outils intelligents", "IA Conformité", "Automatisation de la conformité"],
    pt: ["IA Segurança", "Detecção de transações anômalas", "IA Monitoramento de Riscos", "Análise de riscos e padrões", "IA Assistência Financeira", "Ferramentas inteligentes", "IA Conformidade", "Automação de conformidade"],
    de: ["KI-Sicherheit", "Erkennung anomaler Transaktionen", "KI-Risikoüberwachung", "Risiko- und Musteranalyse", "KI-Finanzhilfe", "Intelligente Werkzeuge", "KI-Compliance", "Compliance-Automatisierung"],
    zh: ["AI安全", "异常交易检测", "AI风险监控", "风险与模式分析", "AI金融助手", "智能工具", "AI合规", "合规自动化"],
    ar: ["أمان الذكاء الاصطناعي", "كشف المعاملات الغير الطارئة", "مراقبة المخاطر بالذكاء الاصطناعي", "تحليل المخاطر والأنماط", "مساعدة مالية بالذكاء الاصطناعي", "أدوات ذكية للمستخدمين", "الامتثال بالذكاء الاصطناعي", "أتمتاث الامتثال"],
  },
  "dex.features": {
    en: ["Asset swap", "Liquidity pools", "Multi-chain interoperability", "Market tools", "Smart contracts", "Decentralized governance"],
    es: ["Swap de activos", "Pools de liquidez", "Interoperabilidad multicadena", "Herramientas de mercado", "Smart contracts", "Gobernanza descentralizada"],
    fr: ["Échange d'actifs", "Pools de liquidité", "Interopérabilité multichaîne", "Outils de marché", "Contrats intelligents", "Gouvernance décentralisée"],
    pt: ["Troca de ativos", "Pools de liquidez", "Interoperabilidade multichain", "Ferramentas de mercado", "Contratos inteligentes", "Governança descentralizada"],
    de: ["Asset-Swap", "Liquiditätspools", "Multichain-Interoperabilität", "Marktwerkzeuge", "Smart Contracts", "Dezentrale Governance"],
    zh: ["资产兑换", "流动性池", "多链互操作", "市场工具", "智能合约", "去中心化治理"],
    ar: ["تبادل الأصول", "مجمعات السيولة", "تشابكية متعددة السلسلة", "أدوات السوق", "العقود الذكية", "الحكم اللامركزي"],
  },
  "qfspay.features": {
    en: ["Digital payments", "P2P transfers", "Commercial payments", "Asset conversion", "Developer APIs", "Enterprise solutions"],
    es: ["Pagos digitales", "Transferencias P2P", "Pagos comerciales", "Conversión de activos", "APIs para desarrolladores", "Soluciones empresariales"],
    fr: ["Paiements numériques", "Transferts P2P", "Paiements commerciaux", "Conversion d'actifs", "APIs développeur", "Solutions d'entreprise"],
    pt: ["Pagamentos digitais", "Transferências P2P", "Pagamentos comerciais", "Conversão de ativos", "APIs para desenvolvedores", "Soluções empresariais"],
    de: ["Digitale Zahlungen", "P2P-Überweisungen", "Kommerzielle Zahlungen", "Asset-Umwandlung", "Entwickler-APIs", "Unternehmenslösungen"],
    zh: ["数字支付", "P2P转账", "商业支付", "资产兑换", "开发者API", "企业解决方案"],
    ar: ["الدفع الرقمي", "تحويلات P2P", "الدفع التجاري", "تحويل الأصول", "APIs للمطورين", "حلول مؤسسية"],
  },
};

export function useT() {
  const { lang } = useLangStore();
  return (key: string): string => t[key]?.[lang] ?? key;
}

export function useTD() {
  const { lang } = useLangStore();
  return (key: string): string[] => td[key]?.[lang] ?? [];
}
