#!/usr/bin/env python3
"""Fix ALL translation issues across the QFS website."""

# ============================================================================
# 1. GENERATE COMPLETE lang-store.ts
# ============================================================================

LANGS = ["en", "es", "fr", "pt", "de", "zh", "ar", "th"]

def tr(data):
    """Build a Lang record from a dict with at least 'en' key. Missing langs fall back to en."""
    return "{ " + ", ".join(f'{l}: {json.dumps(data.get(l, data["en"]))}' for l in LANGS) + " }"

def tra(data):
    """Build a Lang record for arrays (td)."""
    return "{ " + ", ".join(f'{l}: {json.dumps(data.get(l, data["en"]))}' for l in LANGS) + " }"

import json

# All string translations
t_keys = {
    # === ALLIANCES ===
    "all.arab.name": {"en":"Al Arab","es":"Al Arab","fr":"Al Arab","pt":"Al Arab","de":"Al Arab","zh":"Al Arab","ar":"Al Arab","th":"Al Arab"},
    "all.arab.tag": {"en":"Regional Expansion","es":"Expansión Regional","fr":"Expansion Régionale","pt":"Expansão Regional","de":"Regionale Expansion","zh":"区域扩张","ar":"التوسع الإقليمي","th":"การขยายตัวในภูมิภาค"},
    "all.desc": {"en":"QFS builds bridges of collaboration with organizations and governments for a truly global financial infrastructure.","es":"QFS construye puentes de colaboración con organizaciones y gobiernos para una infraestructura financiera verdaderamente global.","fr":"QFS construit des ponts de collaboration avec des organisations et des gouvernements pour une infrastructure financière véritablement mondiale.","pt":"QFS constrói pontes de colaboração com organizações e governos para uma infraestrutura financeira verdadeiramente global.","de":"QFS baut Kooperationsbrücken mit Organisationen und Regierungen für eine wirklich globale Finanzinfrastruktur.","zh":"QFS与组织和政府建立合作桥梁，打造真正全球化的金融基础设施。","ar":"يبني QFS جسور تعاون مع المنظمات والحكومات لبناء بنية مالية عالمية حقيقية.","th":"QFS สร้างสะพานความร่วมมือกับองค์กรและรัฐบาลเพื่อสร้างโครงสร้างพื้นฐานทางการเงินระดับโลกที่แท้จริง"},
    "all.gcrm.name": {"en":"GCRM Alliance","es":"Alianza GCRM","fr":"Alliance GCRM","pt":"Aliança GCRM","de":"GCRM-Allianz","zh":"GCRM联盟","ar":"تحالف GCRM","th":"พันธมิตร GCRM"},
    "all.gcrm.tag": {"en":"Strategic Partner","es":"Socio Estratégico","fr":"Partenaire Stratégique","pt":"Parceiro Estratégico","de":"Strategischer Partner","zh":"战略合作伙伴","ar":"شريك استراتيجي","th":"พันธมิตรเชิงกลยุทธ์"},
    "all.gov.name": {"en":"Government Currencies","es":"Monedas de Gobiernos","fr":"Monnaies Gouvernementales","pt":"Moedas Governamentais","de":"Regierungswährungen","zh":"政府货币","ar":"العملات الحكومية","th":"สกุลเงินรัฐบาล"},
    "all.gov.tag": {"en":"Digital Government","es":"Gobierno Digital","fr":"Gouvernement Numérique","pt":"Governo Digital","de":"Digitale Regierung","zh":"数字政府","ar":"الحكومة الرقمية","th":"รัฐบาลดิจิทัล"},
    "all.subtitle": {"en":"Strategic Alliances","es":"Alianzas Estratégicas","fr":"Alliances Stratégiques","pt":"Alianças Estratégicas","de":"Strategische Allianzen","zh":"战略联盟","ar":"التحالفات الاستراتيجية","th":"พันธมิตรเชิงกลยุทธ์"},
    "all.title": {"en":"Alliances","es":"Alianzas","fr":"Alliances","pt":"Alianças","de":"Allianzen","zh":"联盟","ar":"التحالفات","th":"พันธมิตร"},
    "all.title2": {"en":"Global","es":"Globales","fr":"Mondiales","pt":"Globais","de":"Global","zh":"全球","ar":"العالمية","th":"ระดับโลก"},

    # === CTA ===
    "cta.desc": {"en":"QFS is more than a wallet, more than payments, more than an exchange. It is an integrated digital financial ecosystem designed for the next generation of the global economy.","es":"QFS es más que una wallet, más que pagos, más que un exchange. Es un ecosistema financiero digital integrado diseñado para la próxima generación de la economía global.","fr":"QFS est plus qu'un portefeuille, plus que des paiements, plus qu'un exchange. C'est un écosystème financier numérique intégré conçu pour la prochaine génération de l'économie mondiale.","pt":"QFS é mais que uma carteira, mais que pagamentos, mais que uma exchange. É um ecossistema financeiro digital integrado projetado para a próxima geração da economia global.","de":"QFS ist mehr als eine Wallet, mehr als Zahlungen, mehr als eine Börse. Es ist ein integriertes digitales Finanzökosystem für die nächste Generation der Weltwirtschaft.","zh":"QFS不仅仅是钱包、支付或交易所。它是一个为全球经济下一代设计的集成数字金融生态系统。","ar":"QFS ليس مجرد محفظة أو دفع أو بورصة. إنه نظام مالي رقمي متكامل مصمم للجيل القادم من الاقتصاد العالمي.","th":"QFS ไม่ใช่แค่วอลเล็ต ไม่ใช่แค่การชำระเงิน ไม่ใช่แค่แลกเปลี่ยน แต่เป็นระบบนิเวศทางการเงินดิจิทัลแบบบูรณาการที่ออกแบบมาสำหรับยุคถัดไปของเศรษฐกิจโลก"},
    "cta.join_btn": {"en":"Join Community","es":"Unirse a la Comunidad","fr":"Rejoindre la Communauté","pt":"Junte-se à Comunidade","de":"Gemeinschaft beitreten","zh":"加入社区","ar":"انضم إلى المجتمع","th":"เข้าร่วมชุมชน"},
    "cta.title1": {"en":"Building the Future","es":"Construyendo el Futuro","fr":"Construire l'Avenir","pt":"Construindo o Futuro","de":"Die Zukunft aufbauen","zh":"构建未来","ar":"بناء المستقبل","th":"สร้างอนาคต"},
    "cta.title2": {"en":"of Digital Finance","es":"de las Finanzas Digitales","fr":"des Finances Numériques","pt":"das Finanças Digitais","de":"der Digitalen Finanzen","zh":"数字金融的未来","ar":"للمال الرقمي","th":"แห่งการเงินดิจิทัล"},

    # === ECOSYSTEM ===
    "eco.desc": {"en":"Modular financial architecture integrating different services within a single digital ecosystem.","es":"Arquitectura financiera modular que integra diferentes servicios dentro de un mismo ecosistema digital.","fr":"Architecture financière modulaire intégrant différents services au sein d'un seul écosystème numérique.","pt":"Arquitetura financeira modular que integra diferentes serviços dentro de um único ecossistema digital.","de":"Modulare Finanzarchitektur, die verschiedene Dienste in einem einzigen digitalen Ökosystem integriert.","zh":"模块化金融架构，在单一数字生态系统中整合不同服务。","ar":"هيكل مالي موديولار يدمج خدمات مختلفة ضمن نظام رقمي متكامل.","th":"สถาปัตยกรรมทางการเงินแบบโมดูลาร์ที่ผสานรวมบริการต่างๆ ไว้ในระบบนิเวศดิจิทัลเดียว"},
    "eco.subtitle": {"en":"The Ecosystem","es":"El Ecosistema","fr":"L'Écosystème","pt":"O Ecossistema","de":"Das Ökosystem","zh":"生态系统","ar":"النظام البيئي","th":"ระบบนิเวศ"},
    "eco.title": {"en":"QFS Ecosystem","es":"Ecosistema QFS","fr":"Écosystème QFS","pt":"Ecossistema QFS","de":"QFS Ökosystem","zh":"QFS 生态系统","ar":"نظام QFS البيئي","th":"ระบบนิเวศ QFS"},

    # === FAQ ===
    "faq.subtitle": {"en":"FAQ","es":"Preguntas Frecuentes","fr":"FAQ","pt":"Perguntas Frequentes","de":"FAQ","zh":"常见问题","ar":"الأسئلة الشائعة","th":"คำถามที่พบบ่อย"},
    "faq.title": {"en":"Frequent Questions","es":"Preguntas Frecuentes","fr":"Questions Fréquentes","pt":"Perguntas Frequentes","de":"Häufige Fragen","zh":"常见问题","ar":"أسئلة شائعة","th":"คำถามที่พบบ่อย"},

    # === FOOTER ===
    "foot.alliances": {"en":"Alliances","es":"Alianzas","fr":"Alliances","pt":"Alianças","de":"Allianzen","zh":"联盟","ar":"التحالفات","th":"พันธมิตร"},
    "foot.copyright.prefix": {"en":"QFS Official","es":"QFS Official","fr":"QFS Official","pt":"QFS Official","de":"QFS Official","zh":"QFS Official","ar":"QFS Official","th":"QFS Official"},
    "foot.copyright.suffix": {"en":"Quantum Financial System.","es":"Sistema Financiero Cuántico.","fr":"Système Financier Quantique.","pt":"Sistema Financeiro Quântico.","de":"Quanten-Finanzsystem.","zh":"量子金融系统。","ar":"نظام المال الكمي.","th":"Quantum Financial System."},
    "foot.desc": {"en":"The Next Generation of Digital Finance. Technology, Security, Decentralization, Innovation.","es":"La próxima generación de las finanzas digitales. Tecnología, Seguridad, Descentralización, Innovación.","fr":"La prochaine génération de la finance numérique. Technologie, Sécurité, Décentralisation, Innovation.","pt":"A próxima geração das finanças digitais. Tecnologia, Segurança, Descentralização, Inovação.","de":"Die nächste Generation der digitalen Finanzen. Technologie, Sicherheit, Dezentralisierung, Innovation.","zh":"数字金融的下一代。技术、安全、去中心化、创新。","ar":"الجيل القادم من المال الرقمي. التكنولوجيا، الأمان، اللامركزية، الابتكار.","th":"รุ่นถัดไปของการเงินดิจิทัล เทคโนโลยี ความปลอดภัย การกระจายอำนาจ นวัตกรรม"},
    "foot.products": {"en":"Products","es":"Productos","fr":"Produits","pt":"Produtos","de":"Produkte","zh":"产品","ar":"المنتجات","th":"สินค้า"},
    "foot.resources": {"en":"Resources","es":"Recursos","fr":"Ressources","pt":"Recursos","de":"Ressourcen","zh":"资源","ar":"الموارد","th":"ทรัพยากร"},
    "foot.tag.connectivity": {"en":"Global Connectivity","es":"Conectividad Global","fr":"Connectivité Mondiale","pt":"Conectividade Global","de":"Globale Vernetzung","zh":"全球连接","ar":"الاتصال العالمي","th":"การเชื่อมต่อระดับโลก"},
    "foot.tag.decentralization": {"en":"Decentralization","es":"Descentralización","fr":"Décentralisation","pt":"Descentralização","de":"Dezentralisierung","zh":"去中心化","ar":"اللامركزية","th":"การกระจายอำนาจ"},
    "foot.tag.finance": {"en":"Digital Finance","es":"Finanzas Digitales","fr":"Finances Numériques","pt":"Finanças Digitais","de":"Digitale Finanzen","zh":"数字金融","ar":"المال الرقمي","th":"การเงินดิจิทัล"},
    "foot.tag.innovation": {"en":"Innovation","es":"Innovación","fr":"Innovation","pt":"Inovação","de":"Innovation","zh":"创新","ar":"الابتكار","th":"นวัตกรรม"},
    "foot.tag.security": {"en":"Security","es":"Seguridad","fr":"Sécurité","pt":"Segurança","de":"Sicherheit","zh":"安全","ar":"الأمان","th":"ความปลอดภัย"},
    "foot.tag.technology": {"en":"Technology","es":"Tecnología","fr":"Technologie","pt":"Tecnologia","de":"Technologie","zh":"技术","ar":"التكنولوجيا","th":"เทคโนโลยี"},

    # === HERO ===
    "hero.badge": {"en":"QUANTUM FINANCIAL SYSTEM","es":"SISTEMA FINANCIERO CUÁNTICO","fr":"SYSTÈME FINANCIER QUANTIQUE","pt":"SISTEMA FINANCEIRO QUÂNTICO","de":"QUANTEN-FINANZSYSTEM","zh":"量子金融系统","ar":"نظام المال الكمي","th":"QUANTUM FINANCIAL SYSTEM"},
    "hero.desc": {"en":"QFS Official develops a new digital financial infrastructure integrating blockchain, artificial intelligence, advanced cryptographic security, digital payments and decentralized financial services.","es":"QFS Official desarrolla una nueva infraestructura financiera digital que integra blockchain, inteligencia artificial, seguridad criptográfica avanzada, pagos digitales y servicios financieros descentralizados.","fr":"QFS Official développe une nouvelle infrastructure financière numérique intégrant la blockchain, l'intelligence artificielle, la sécurité cryptographique avancée, les paiements numériques et les services financiers décentralisés.","pt":"QFS Official desenvolve uma nova infraestrutura financeira digital integrando blockchain, inteligência artificial, segurança criptográfica avançada, pagamentos digitais e serviços financeiros descentralizados.","de":"QFS Official entwickelt eine neue digitale Finanzinfrastruktur, die Blockchain, Künstliche Intelligenz, fortschrittliche Kryptografie, digitale Zahlungen und dezentrale Finanzdienstleistungen integriert.","zh":"QFS Official 开发了一套新的数字金融基础设施，整合区块链、人工智能、高级加密安全、数字支付和去中心化金融服务。","ar":"تطور QFS Official بنية مالية رقمية جديدة تدمج البلوكتشين والذكاء الاصطناعي والأمن التشفيري المتقدم والدفع الرقمي والخدمات المالية اللامركزية.","th":"QFS Official พัฒนาโครงสร้างพื้นฐานทางการเงินดิจิทัลใหม่ที่ผสานรวมบล็อกเชน ปัญญาประดิษฐ์ ความปลอดภัยทางการเข้ารหัสขั้นสูง การชำระเงินดิจิทัล และบริการทางการเงินแบบกระจายศูนย์"},
    "hero.explore_btn": {"en":"Explore QFS","es":"Explorar QFS","fr":"Explorer QFS","pt":"Explorar QFS","de":"QFS entdecken","zh":"探索 QFS","ar":"استكشاف QFS","th":"สำรวจ QFS"},
    "hero.qfspay": {"en":"QFSPay","es":"QFSPay","fr":"QFSPay","pt":"QFSPay","de":"QFSPay","zh":"QFSPay","ar":"QFSPay","th":"QFSPay"},
    "hero.tags.connectivity": {"en":"Global Connectivity","es":"Conectividad Global","fr":"Connectivité Mondiale","pt":"Conectividade Global","de":"Globale Vernetzung","zh":"全球连接","ar":"الاتصال العالمي","th":"การเชื่อมต่อระดับโลก"},
    "hero.tags.decentralization": {"en":"Decentralization","es":"Descentralización","fr":"Décentralisation","pt":"Descentralização","de":"Dezentralisierung","zh":"去中心化","ar":"اللامركزية","th":"การกระจายอำนาจ"},
    "hero.tags.finance": {"en":"Digital Finance","es":"Finanzas Digitales","fr":"Finances Numériques","pt":"Finanças Digitais","de":"Digitale Finanzen","zh":"数字金融","ar":"المال الرقمي","th":"การเงินดิจิทัล"},
    "hero.tags.security": {"en":"Security","es":"Seguridad","fr":"Sécurité","pt":"Segurança","de":"Sicherheit","zh":"安全","ar":"الأمان","th":"ความปลอดภัย"},
    "hero.tags.technology": {"en":"Technology","es":"Tecnología","fr":"Technologie","pt":"Tecnologia","de":"Technologie","zh":"技术","ar":"التكنولوجيا","th":"เทคโนโลยี"},
    "hero.title1": {"en":"The Future of","es":"El Futuro de las","fr":"L'Avenir des","pt":"O Futuro das","de":"Die Zukunft der","zh":"数字金融的","ar":"مستقبل","th":"อนาคตของ"},
    "hero.title2": {"en":"Digital Finance","es":"Finanzas Digitales","fr":"Finances Numériques","pt":"Finanças Digitais","de":"Digitalen Finanzen","zh":"未来","ar":"المال الرقمي","th":"การเงินดิจิทัล"},
    "hero.wallet": {"en":"QFS Wallet","es":"QFS Wallet","fr":"QFS Wallet","pt":"QFS Wallet","de":"QFS Wallet","zh":"QFS Wallet","ar":"QFS Wallet","th":"QFS Wallet"},

    # === LANGUAGE NAMES ===
    "lang.ar": {"en":"العربية","es":"Árabe","fr":"Arabe","pt":"Árabe","de":"Arabisch","zh":"阿拉伯语","ar":"العربية","th":"อาหรับ"},
    "lang.de": {"en":"Deutsch","es":"Alemán","fr":"Allemand","pt":"Alemão","de":"Deutsch","zh":"德语","ar":"الألمانية","th":"เยอรมัน"},
    "lang.en": {"en":"English","es":"Inglés","fr":"Anglais","pt":"Inglês","de":"Englisch","zh":"英语","ar":"الإنجليزية","th":"อังกฤษ"},
    "lang.es": {"en":"Español","es":"Español","fr":"Espagnol","pt":"Espanhol","de":"Spanisch","zh":"西班牙语","ar":"الإسبانية","th":"สเปน"},
    "lang.fr": {"en":"Français","es":"Francés","fr":"Français","pt":"Francês","de":"Französisch","zh":"法语","ar":"الفرنسية","th":"ฝรั่งเศส"},
    "lang.pt": {"en":"Português","es":"Portugués","fr":"Portugais","pt":"Português","de":"Portugiesisch","zh":"葡萄牙语","ar":"البرتغالية","th":"โปรตุเกส"},
    "lang.th": {"en":"ภาษาไทย","es":"Tailandés","fr":"Thaï","pt":"Tailandês","de":"Thailändisch","zh":"泰语","ar":"التايلاندية","th":"ไทย"},
    "lang.zh": {"en":"中文","es":"Chino","fr":"Chinois","pt":"Chinês","de":"Chinesisch","zh":"中文","ar":"الصينية","th":"จีน"},

    # === NAV ===
    "nav.explore": {"en":"Explore QFS","es":"Explorar QFS","fr":"Explorer QFS","pt":"Explorar QFS","de":"QFS entdecken","zh":"探索 QFS","ar":"استكشاف QFS","th":"สำรวจ QFS"},
    "nav.home": {"en":"Home","es":"Inicio","fr":"Accueil","pt":"Inicio","de":"Startseite","zh":"首页","ar":"الرئيسية","th":"หน้าแรก"},
    "nav.join": {"en":"Join Community","es":"Unirse a la Comunidad","fr":"Rejoindre la Communauté","pt":"Junte-se à Comunidade","de":"Gemeinschaft beitreten","zh":"加入社区","ar":"انضم إلى المجتمع","th":"เข้าร่วมชุมชน"},
    "nav.portal": {"en":"Portal","es":"Portal","fr":"Portail","pt":"Portal","de":"Portal","zh":"门户","ar":"البوابة","th":"พอร์ทัล"},
    "nav.roadmap": {"en":"Roadmap","es":"Roadmap","fr":"Feuille de Route","pt":"Roteiro","de":"Roadmap","zh":"路线图","ar":"خريطة الطريق","th":"แผนงาน"},
    "nav.whitepaper": {"en":"White Paper","es":"Libro Blanco","fr":"Livre Blanc","pt":"Livro Branco","de":"Whitepaper","zh":"白皮书","ar":"الوثيقة التفصيلية","th":"เอกสารขาว"},

    # === PILLARS ===
    "pil.desc": {"en":"QFS proposes a new financial architecture based on principles that will transform the digital economy.","es":"QFS propone una nueva arquitectura financiera basada en principios que transformarán la economía digital.","fr":"QFS propose une nouvelle architecture financière basée sur des principes qui transformeront l'économie numérique.","pt":"QFS propõe uma nova arquitetura financeira baseada em princípios que transformarão a economia digital.","de":"QFS schlägt eine neue Finanzarchitektur vor, die auf Prinzipien basiert, die die digitale Wirtschaft transformieren werden.","zh":"QFS 提出了一种基于将改变数字经济的原则的新金融架构。","ar":"يقترح QFS هيكلاً مالياً جديداً قائماً على مبادئ ستحول الاقتصاد الرقمي.","th":"QFS เสนอสถาปัตยกรรมทางการเงินใหม่บนพื้นฐานหลักการที่จะเปลี่ยนแปลงเศรษฐกิจดิจิทัล"},
    "pil.subtitle": {"en":"Architecture","es":"Arquitectura","fr":"Architecture","pt":"Arquitetura","de":"Architektur","zh":"架构","ar":"الهيكل المعماري","th":"สถาปัตยกรรม"},
    "pil.title1": {"en":"Five","es":"Cinco","fr":"Cinq","pt":"Cinco","de":"Fünf","zh":"五大","ar":"خمسة","th":"ห้า"},
    "pil.title2": {"en":"Pillars","es":"Pilares","fr":"Piliers","pt":"Pilares","de":"Säulen","zh":"支柱","ar":"ركائز","th":"เสาหลัก"},
    "pil.title3": {"en":"Fundamental","es":"Fundamentales","fr":"Fondamentaux","pt":"Fundamentais","de":"Grundlegend","zh":"基础","ar":"أساسية","th":"พื้นฐาน"},

    # === PORTAL ===
    "portal.badge": {"en":"PORTAL","es":"PORTAL","fr":"PORTAIL","pt":"PORTAL","de":"PORTAL","zh":"门户","ar":"البوابة","th":"พอร์ทัล"},
    "portal.card.desc": {"en":"Your QFS digital assets available for everyday purchases through the QFSPay card.","es":"Tus activos digitales QFS disponibles para compras cotidianas a través de la tarjeta QFSPay.","fr":"Vos actifs numériques QFS disponibles pour les achats quotidiens via la carte QFSPay.","pt":"Seus ativos digitais QFS disponíveis para compras diárias através do cartão QFSPay.","de":"Ihre QFS-digitalen Assets für tägliche Einkäufe verfügbar über die QFSPay-Karte.","zh":"您的QFS数字资产可通过QFSPay卡用于日常购买。","ar":"أصولك الرقمية QFS متاحة للمشتريات اليومية عبر بطاقة QFSPay.","th":"สินทรัพย์ดิจิทัล QFS ของคุณพร้อมใช้สำหรับการซื้อของในชีวิตประจำวันผ่านบัตร QFSPay"},
    "portal.card.title": {"en":"QFSPay Card","es":"Tarjeta QFSPay","fr":"Carte QFSPay","pt":"Cartão QFSPay","de":"QFSPay Karte","zh":"QFSPay 卡","ar":"بطاقة QFSPay","th":"บัตร QFSPay"},
    "portal.currencies": {"en":"Supported Currencies","es":"Monedas Soportadas","fr":"Devises Prises en Charge","pt":"Moedas Suportadas","de":"Unterstützte Währungen","zh":"支持的货币","ar":"العملات المدعومة","th":"สกุลเงินที่รองรับ"},
    "portal.desc": {"en":"Explore the currencies, features and services available within the QFS ecosystem.","es":"Explore las monedas, funciones y servicios disponibles dentro del ecosistema QFS.","fr":"Explorez les devises, fonctionnalités et services disponibles dans l'écosystème QFS.","pt":"Explore as moedas, recursos e serviços disponíveis no ecossistema QFS.","de":"Erkunden Sie die Währungen, Funktionen und Dienste im QFS-Ökosystem.","zh":"探索QFS生态系统中可用的货币、功能和服务。","ar":"استكشف العملات والميزات والخدمات المتاحة في نظام QFS.","th":"สำรวจสกุลเงิน คุณสมบัติ และบริการที่มีอยู่ในระบบนิเวศ QFS"},
    "portal.features": {"en":"Platform Features","es":"Características de la Plataforma","fr":"Fonctionnalités de la Plateforme","pt":"Recursos da Plataforma","de":"Plattform-Funktionen","zh":"平台功能","ar":"ميزات المنصة","th":"คุณสมบัติแพลตฟอร์ม"},
    "portal.subtitle": {"en":"Digital Financial Gateway","es":"Puerta de Acceso Financiera Digital","fr":"Passerelle Financière Numérique","pt":"Portal Financeiro Digital","de":"Digitales Finanzportal","zh":"数字金融网关","ar":"البوابة المالية الرقمية","th":"ประตูทางการเงินดิจิทัล"},
    "portal.title": {"en":"QFS Portal","es":"Portal QFS","fr":"Portail QFS","pt":"Portal QFS","de":"QFS Portal","zh":"QFS 门户","ar":"بوابة QFS","th":"พอร์ทัล QFS"},

    # === PRODUCTS ===
    "prod.ai.subtitle": {"en":"Intelligent Finance","es":"Finanzas Inteligentes","fr":"Finance Intelligente","pt":"Finanças Inteligentes","de":"Intelligente Finanzen","zh":"智能金融","ar":"المال الذكي","th":"การเงินอัจฉริยะ"},
    "prod.ai.title": {"en":"QFS + AI","es":"QFS + IA","fr":"QFS + IA","pt":"QFS + IA","de":"QFS + KI","zh":"QFS + AI","ar":"QFS + AI","th":"QFS + AI"},
    "prod.cards.desc": {"en":"Connects the QFS digital ecosystem with real-world physical and digital payment solutions.","es":"Conecta el ecosistema digital QFS con soluciones de pago físicas y digitales del mundo real.","fr":"Connecte l'écosystème numérique QFS avec des solutions de paiement physiques et numériques du monde réel.","pt":"Conecta o ecossistema digital QFS com soluções de pagamento físicas e digitais do mundo real.","de":"Verbindet das QFS-digitale Ökosystem mit physischen und digitalen Zahlungslösungen der realen Welt.","zh":"将QFS数字生态系统与现实世界的实体和数字支付解决方案连接起来。","ar":"يربط نظام QFS الرقمي بحلول الدفع الفيزيائية والرقمية في العالم الحقيقي.","th":"เชื่อมต่อระบบนิเวศดิจิทัล QFS กับโซลูชันการชำระเงินทางกายภาพและดิจิทัลในโลกแห่งความเป็นจริง"},
    "prod.cards.subtitle": {"en":"Digital-to-Physical","es":"Digital a Físico","fr":"Numérique vers Physique","pt":"Digital para Físico","de":"Digital-zu-Physisch","zh":"数字到实体","ar":"رقمي إلى فيزيائي","th":"ดิจิทัลสู่กายภาพ"},
    "prod.cards.title": {"en":"QFS Quantum Cards","es":"QFS Quantum Cards","fr":"QFS Quantum Cards","pt":"QFS Quantum Cards","de":"QFS Quantum Cards","zh":"QFS Quantum Cards","ar":"QFS Quantum Cards","th":"QFS Quantum Cards"},
    "prod.cards.wallet": {"en":"Wallet","es":"Wallet","fr":"Wallet","pt":"Wallet","de":"Wallet","zh":"钱包","ar":"محفظة","th":"วอลเล็ต"},
    "prod.cards.payments": {"en":"Payments","es":"Pagos","fr":"Paiements","pt":"Pagamentos","de":"Zahlungen","zh":"支付","ar":"الدفع","th":"การชำระเงิน"},
    "prod.dex.desc": {"en":"Decentralized platform for exchanging digital assets with access to ecosystem markets and liquidity.","es":"Plataforma descentralizada para el intercambio de activos digitales con acceso a mercados y liquidez del ecosistema.","fr":"Plateforme décentralisée pour l'échange d'actifs numériques avec accès aux marchés et à la liquidité de l'écosystème.","pt":"Plataforma descentralizada para troca de ativos digitais com acesso a mercados e liquidez do ecossistema.","de":"Dezentrale Plattform zum Austausch digitaler Assets mit Zugang zu Ökosystem-Märkten und Liquidität.","zh":"去中心化的数字资产交易平台，可访问生态系统市场和流动性。","ar":"منصة لامركزية لتبادل الأصول الرقمية مع الوصول إلى أسواق وسيولة النظام.","th":"แพลตฟอร์มแบบกระจายศูนย์สำหรับแลกเปลี่ยนสินทรัพย์ดิจิทัลพร้อมเข้าถึงตลาดและสภาพคล่องของระบบนิเวศ"},
    "prod.dex.subtitle": {"en":"Decentralized Trading","es":"Trading Descentralizado","fr":"Trading Décentralisé","pt":"Trading Descentralizado","de":"Dezentraler Handel","zh":"去中心化交易","ar":"التداول اللامركزي","th":"การซื้อขายแบบกระจายศูนย์"},
    "prod.dex.title": {"en":"QFS Exchange DEX","es":"QFS Exchange DEX","fr":"QFS Exchange DEX","pt":"QFS Exchange DEX","de":"QFS Exchange DEX","zh":"QFS Exchange DEX","ar":"QFS Exchange DEX","th":"QFS Exchange DEX"},
    "prod.qfspay.desc": {"en":"Digital payments for a connected economy. Facilitates the use of digital assets for everyday and commercial operations.","es":"Pagos digitales para una economía conectada. Facilita la utilización de activos digitales para operaciones cotidianas y comerciales.","fr":"Paiements numériques pour une économie connectée. Facilite l'utilisation d'actifs numériques pour les opérations quotidiennes et commerciales.","pt":"Pagamentos digitais para uma economia conectada. Facilita o uso de ativos digitais para operações diárias e comerciais.","de":"Digitale Zahlungen für eine vernetzte Wirtschaft. Erleichtert die Nutzung digitaler Assets für alltägliche und kommerzielle Operationen.","zh":"为互联经济提供数字支付。促进数字资产在日常和商业运营中的使用。","ar":"دفع رقمي لاقتصاد متصل. يسهل استخدام الأصول الرقمية للعمليات اليومية والتجارية.","th":"การชำระเงินดิจิทัลสำหรับเศรษฐกิจที่เชื่อมต่อกัน อำนวยความสะดวกในการใช้สินทรัพย์ดิจิทัลสำหรับการดำเนินงานในชีวิตประจำวันและธุรกิจ"},
    "prod.qfspay.subtitle": {"en":"Digital Payments","es":"Pagos Digitales","fr":"Paiements Numériques","pt":"Pagamentos Digitais","de":"Digitale Zahlungen","zh":"数字支付","ar":"الدفع الرقمي","th":"การชำระเงินดิจิทัล"},
    "prod.qfspay.title": {"en":"QFSPay","es":"QFSPay","fr":"QFSPay","pt":"QFSPay","de":"QFSPay","zh":"QFSPay","ar":"QFSPay","th":"QFSPay"},
    "prod.subtitle": {"en":"Products","es":"Productos","fr":"Produits","pt":"Produtos","de":"Produkte","zh":"产品","ar":"المنتجات","th":"สินค้า"},
    "prod.title": {"en":"QFS Products","es":"Productos QFS","fr":"Produits QFS","pt":"Produtos QFS","de":"QFS Produkte","zh":"QFS 产品","ar":"منتجات QFS","th":"สินค้า QFS"},
    "prod.wallet.balance": {"en":"Total Balance","es":"Balance Total","fr":"Solde Total","pt":"Saldo Total","de":"Gesamtguthaben","zh":"总余额","ar":"الرصيد الإجمالي","th":"ยอดคงเหลือทั้งหมด"},
    "prod.wallet.desc": {"en":"The user's entry point to the QFS ecosystem. Manage different types of digital assets from a single interface with advanced security.","es":"El punto de acceso del usuario al ecosistema QFS. Gestione diferentes tipos de activos digitales desde una única interfaz con seguridad avanzada.","fr":"Le point d'accès des utilisateurs à l'écosystème QFS. Gérez différents types d'actifs numériques depuis une seule interface avec une sécurité avancée.","pt":"O ponto de acesso do usuário ao ecossistema QFS. Gerencie diferentes tipos de ativos digitais de uma única interface com segurança avançada.","de":"Der Zugangspunkt der Benutzer zum QFS-Ökosystem. Verwalten Sie verschiedene digitale Asset-Typen von einer einzigen Oberfläche mit fortschrittlicher Sicherheit.","zh":"用户进入QFS生态系统的入口。通过具有高级安全性的单一界面管理各种数字资产。","ar":"نقطة دخول المستخدم إلى نظام QFS. إدارة أنواع مختلفة من الأصول الرقمية من واجهة واحدة بأمان متقدم.","th":"จุดเข้าถึงระบบนิเวศ QFS ของผู้ใช้ จัดการสินทรัพย์ดิจิทัลหลายประเภทจากอินเทอร์เฟซเดียวพร้อมความปลอดภัยขั้นสูง"},
    "prod.wallet.month": {"en":"this month","es":"este mes","fr":"ce mois","pt":"este mês","de":"diesen Monat","zh":"本月","ar":"هذا الشهر","th":"เดือนนี้"},
    "prod.wallet.subtitle": {"en":"Your Digital Financial Hub","es":"Tu Centro Financiero Digital","fr":"Votre Hub Financier Numérique","pt":"Seu Hub Financeiro Digital","de":"Ihr Digitales Finanzzentrum","zh":"您的数字金融中心","ar":"مركزك المالي الرقمي","th":"ศูนย์กลางการเงินดิจิทัลของคุณ"},
    "prod.wallet.title": {"en":"QFS Wallet","es":"QFS Wallet","fr":"QFS Wallet","pt":"QFS Wallet","de":"QFS Wallet","zh":"QFS Wallet","ar":"QFS Wallet","th":"QFS Wallet"},

    # === SECURITY ===
    "sec.desc": {"en":"Security is one of the fundamental pillars of the QFS ecosystem. Designed to evolve alongside new digital threats through a multi-layered security architecture.","es":"La seguridad constituye uno de los pilares fundamentales del ecosistema QFS. Diseñado para evolucionar con las nuevas amenazas digitales mediante una arquitectura de seguridad multicapa.","fr":"La sécurité est l'un des piliers fondamentaux de l'écosystème QFS. Conçu pour évoluer avec les nouvelles menaces numériques grâce à une architecture de sécurité multicouche.","pt":"A segurança é um dos pilares fundamentais do ecossistema QFS. Projetado para evoluir junto com as novas ameaças digitais por meio de uma arquitetura de segurança multicamadas.","de":"Sicherheit ist einer der Grundpfeiler des QFS-Ökosystems. Konzipiert, um sich mit neuen digitalen Bedrohungen durch eine mehrschichtige Sicherheitsarchitektur weiterzuentwickeln.","zh":"安全是QFS生态系统的基本支柱之一。通过多层安全架构设计，能够随新型数字威胁一起演进。","ar":"الأمان هو أحد الركائز الأساسية لنظام QFS. مصمم للتطور مع التهديدات الرقمية الجديدة من خلال هيكل أماني متعدد الطبقات.","th":"ความปลอดภัยเป็นหนึ่งในเสาหลักพื้นฐานของระบบนิเวศ QFS ออกแบบมาให้วิวัฒนาการพร้อมกับภัยคุกคามดิจิทัลใหม่ๆ ผ่านสถาปัตยกรรมความปลอดภัยหลายชั้น"},
    "sec.subtitle": {"en":"Security","es":"Seguridad","fr":"Sécurité","pt":"Segurança","de":"Sicherheit","zh":"安全","ar":"الأمان","th":"ความปลอดภัย"},
    "sec.title": {"en":"QFS Security","es":"Seguridad QFS","fr":"Sécurité QFS","pt":"Segurança QFS","de":"QFS Sicherheit","zh":"QFS 安全","ar":"أمان QFS","th":"QFS Security"},

    # === TOKEN ALLOCATION ===
    "token.alloc.footnote": {"en":"* Reference supply subject to adjustments based on ecosystem development.","es":"* Suministro de referencia sujeto a ajustes según el desarrollo del ecosistema.","fr":"* Offre de référence soumise à des ajustements en fonction du développement de l'écosystème.","pt":"* Oferta de referência sujeita a ajustes com base no desenvolvimento do ecossistema.","de":"* Referenzangebot kann基于生态系统开发进行调整。","zh":"* 参考供应量可能根据生态系统开发进行调整。","ar":"* العرض المرجعي خاضع للتعديلات بناءً على تطوير النظام.","th":"* อุปทานอ้างอิงอาจมีการปรับเปลี่ยนตามการพัฒนาของระบบนิเวศ"},
    "token.alloc.subtitle": {"en":"Token Distribution","es":"Distribución del Token","fr":"Distribution du Token","pt":"Distribuição do Token","de":"Token-Verteilung","zh":"代币分配","ar":"توزيع العملة","th":"การกระจายโทเคน"},
    "token.alloc.supply": {"en":"Reference Supply*","es":"Suministro de Referencia*","fr":"Offre de Référence*","pt":"Oferta de Referência*","de":"Referenzangebot*","zh":"参考供应量*","ar":"العرض المرجعي*","th":"อุปทานอ้างอิง*"},
    "token.alloc.title1": {"en":"QFS Token","es":"Token QFS","fr":"Token QFS","pt":"Token QFS","de":"QFS Token","zh":"QFS 代币","ar":"عملة QFS","th":"โทเคน QFS"},
    "token.alloc.title2": {"en":"Allocation","es":"Asignación","fr":"Allocation","pt":"Alocação","de":"Zuteilung","zh":"分配","ar":"التخصيص","th":"การจัดสรร"},

    # === WHY QFS ===
    "why.access": {"en":"Access","es":"Acceso","fr":"Accès","pt":"Acesso","de":"Zugang","zh":"接入","ar":"الوصول","th":"การเข้าถึง"},
    "why.access.desc": {"en":"Financial services accessible from an integrated platform.","es":"Servicios financieros accesibles desde una plataforma integrada.","fr":"Services financiers accessibles depuis une plateforme intégrée.","pt":"Serviços financeiros acessíveis de uma plataforma integrada.","de":"Finanzdienstleistungen zugänglich über eine integrierte Plattform.","zh":"通过集成平台即可访问的金融服务。","ar":"خدمات مالية متاحة من منصة متكاملة.","th":"บริการทางการเงินที่เข้าถึงได้จากแพลตฟอร์มบูรณาการ"},
    "why.innovation": {"en":"Innovation","es":"Innovación","fr":"Innovation","pt":"Inovação","de":"Innovation","zh":"创新","ar":"الابتكار","th":"นวัตกรรม"},
    "why.innovation.desc": {"en":"Blockchain + AI + Cryptography + Digital Finance.","es":"Blockchain + IA + Criptografía + Finanzas Digitales.","fr":"Blockchain + IA + Cryptographie + Finances Numériques.","pt":"Blockchain + IA + Criptografia + Finanças Digitais.","de":"Blockchain + KI + Kryptografie + Digitale Finanzen.","zh":"区块链 + AI + 加密术 + 数字金融。","ar":"البلوكتشين + الذكاء الاصطناعي + التشفير + المال الرقمي.","th":"บล็อกเชน + AI + การเข้ารหัส + การเงินดิจิทัล"},
    "why.interop": {"en":"Interoperability","es":"Interoperabilidad","fr":"Interopérabilité","pt":"Interoperabilidade","de":"Interoperabilität","zh":"互操作性","ar":"التشابكية","th":"การทำงานร่วมกัน"},
    "why.interop.desc": {"en":"Connection between different networks and assets.","es":"Conexión entre diferentes redes y activos.","fr":"Connexion entre différents réseaux et actifs.","pt":"Conexão entre diferentes redes e ativos.","de":"Verbindung zwischen verschiedenen Netzwerken und Assets.","zh":"不同网络和资产之间的连接。","ar":"الترابط بين الشبكات والأصول المختلفة.","th":"การเชื่อมต่อระหว่างเครือข่ายและสินทรัพย์ต่างๆ"},
    "why.security": {"en":"Security","es":"Seguridad","fr":"Sécurité","pt":"Segurança","de":"Sicherheit","zh":"安全","ar":"الأمان","th":"ความปลอดภัย"},
    "why.security.desc": {"en":"Infrastructure designed with security as absolute priority.","es":"Infraestructura diseñada con seguridad como prioridad absoluta.","fr":"Infrastructure conçue avec la sécurité comme priorité absolue.","pt":"Infraestrutura projetada com segurança como prioridade absoluta.","de":"Infrastruktur mit Sicherheit als absolutem Priorität.","zh":"以安全为绝对优先事项设计的基础设施。","ar":"بنية تحتيا الأمان كأولوية مطلقة.","th":"โครงสร้างพื้นฐานที่ออกแบบโดยให้ความปลอดภัยเป็นอันดับหนึ่ง"},
    "why.speed": {"en":"Speed","es":"Velocidad","fr":"Vitesse","pt":"Velocidade","de":"Geschwindigkeit","zh":"速度","ar":"السرعة","th":"ความเร็ว"},
    "why.speed.desc": {"en":"Efficient and scalable digital processing.","es":"Procesamiento digital eficiente y escalable.","fr":"Traitement numérique efficace et évolutif.","pt":"Processamento digital eficiente e escalável.","de":"Effiziente und skalierbare digitale Verarbeitung.","zh":"高效可扩展的数字处理。","ar":"معالجة رقمية فعالة وقابلة للتوسع.","th":"การประมวลผลดิจิทัลที่มีประสิทธิภาพและขยายได้"},
    "why.subtitle": {"en":"Why QFS","es":"Por qué QFS","fr":"Pourquoi QFS","pt":"Por que QFS","de":"Warum QFS","zh":"为什么选QFS","ar":"لماذا QFS","th":"ทำไมต้อง QFS"},
    "why.title": {"en":"Why QFS?","es":"¿Por qué QFS?","fr":"Pourquoi QFS ?","pt":"Por que QFS?","de":"Warum QFS?","zh":"为什么选QFS？","ar":"لماذا QFS؟","th":"ทำไมต้อง QFS?"},
    "why.transparency": {"en":"Transparency","es":"Transparencia","fr":"Transparence","pt":"Transparência","de":"Transparenz","zh":"透明度","ar":"الشفافية","th":"ความโปร่งใส"},
    "why.transparency.desc": {"en":"Blockchain technology and verifiable records.","es":"Tecnología blockchain y registros verificables.","fr":"Technologie blockchain et registres vérifiables.","pt":"Tecnologia blockchain e registros verificáveis.","de":"Blockchain-Technologie und überprüfbare Aufzeichnungen.","zh":"区块链技术和可验证记录。","ar":"تكنولوجيا البلوكتشين وسجلات قابلة للتحقق.","th":"เทคโนโลยีบล็อกเชนและบันทึกที่ตรวจสอบได้"},

    # === ROADMAP ===
    "road.badge": {"en":"ROADMAP","es":"ROADMAP","fr":"FEUILLE DE ROUTE","pt":"ROTEIRO","de":"ROADMAP","zh":"路线图","ar":"خريطة الطريق","th":"แผนงาน"},
    "road.desc": {"en":"Progressive development of the QFS ecosystem through strategic phases, from the base infrastructure to global digital finance.","es":"Desarrollo progresivo del ecosistema QFS a través de fases estratégicas, desde la infraestructura base hasta las finanzas digitales globales.","fr":"Développement progressif de l'écosystème QFS à travers des phases stratégiques, de l'infrastructure de base à la finance numérique mondiale.","pt":"Desenvolvimento progressivo do ecossistema QFS através de fases estratégicas, da infraestrutura bás às finanças digitais globais.","de":"Progressive Entwicklung des QFS-Ökosystems durch strategische Phasen, von der Basisinfrastruktur bis zur globalen digitalen Finanzierung.","zh":"通过战略阶段逐步开发QFS生态系统，从基础设施到全球数字金融。","ar":"التطوير التدريجي لنظام QFS عبر مراحل استراتيجية، من البنية الأساسية إلى المال الرقمي العالمي.","th":"การพัฒนาระบบนิเวศ QFS อย่างเป็นขั้นตอนผ่านช่วงเวลาทางยุทธศาสตร์ ตั้งแต่โครงสร้างพื้นฐานจนถึงการเงินดิจิทัลระดับโลก"},
    "road.eco.desc": {"en":"An interconnected suite of financial services powered by quantum technology.","es":"Una suite interconectada de servicios financieros impulsada por tecnología cuántica.","fr":"Une suite interconnectée de services financiers alimentée par la technologie quantique.","pt":"Um conjunto interconectado de serviços financeiros impulsionado por tecnologia quântica.","de":"Eine verbundene Suite von Finanzdienstleistungen, angetrieben von Quantentechnologie.","zh":"由量子技术驱动的互联金融服务套件。","ar":"مجموعة مترابطة من الخدمات المالية مدعومة بتكنولوجيا الكم.","th":"ชุดบริการทางการเงินที่เชื่อมต่อกันโดยขับเคลื่อนด้วยเทคโนโลยีควอนตัม"},
    "road.eco.dev": {"en":"In Development","es":"En Desarrollo","fr":"En Développement","pt":"Em Desenvolvimento","de":"In Entwicklung","zh":"开发中","ar":"قيد التطوير","th":"อยู่ระหว่างพัฒนา"},
    "road.eco.live": {"en":"Live","es":"Activo","fr":"Actif","pt":"Ativo","de":"Aktiv","zh":"已上线","ar":"نشط","th":"ใช้งานได้"},
    "road.eco.soon": {"en":"Coming Soon","es":"Próximamente","fr":"Prochainement","pt":"Em Breve","de":"Demnächst","zh":"即将推出","ar":"قريباً","th":"เร็วๆ นี้"},
    "road.eco.subtitle": {"en":"Ecosystem Map","es":"Mapa del Ecosistema","fr":"Carte de l'Écosystème","pt":"Mapa do Ecossistema","de":"Ökosystem-Karte","zh":"生态系统图","ar":"خريطة النظام","th":"แผนที่ระบบนิเวศ"},
    "road.phases": {"en":"Development Phases","es":"Fases de Desarrollo","fr":"Phases de Développement","pt":"Fases de Desenvolvimento","de":"Entwicklungsphasen","zh":"开发阶段","ar":"مراحل التطوير","th":"ช่วงการพัฒนา"},
    "road.timeline": {"en":"Timeline","es":"Línea de Tiempo","fr":"Chronologie","pt":"Linha do Tempo","de":"Zeitstrahl","zh":"时间线","ar":"الجدول الزمني","th":"ไทม์ไลน์"},
    "road.title": {"en":"QFS Roadmap","es":"Roadmap QFS","fr":"Feuille de Route QFS","pt":"Roteiro QFS","de":"QFS Roadmap","zh":"QFS 路线图","ar":"خريطة طريق QFS","th":"แผนงาน QFS"},

    # === WHITEPAPER ===
    "wp.badge": {"en":"WHITE PAPER","es":"LIBRO BLANCO","fr":"LIVRE BLANC","pt":"LIVRO BRANCO","de":"WHITEPAPER","zh":"白皮书","ar":"الوثيقة التفصيلية","th":"เอกสารขาว"},
    "wp.confidential": {"en":"Confidential","es":"Confidencial","fr":"Confidentiel","pt":"Confidencial","de":"Vertraulich","zh":"机密","ar":"سري","th":"ลับ"},
    "wp.desc": {"en":"Technical document describing the vision, architecture and progressive development of the Quantum Financial System.","es":"Documento técnico que describe la visión, arquitectura y desarrollo progresivo del Sistema Financiero Cuántico.","fr":"Document technique décrivant la vision, l'architecture et le développement progressif du Système Financier Quantique.","pt":"Documento técnico que descreve a visão, arquitetura e desenvolvimento progressivo do Sistema Financeiro Quântico.","de":"Technisches Dokument beschreiben Vision, Architektur und progressive Entwicklung des Quanten-Finanzsystems.","zh":"描述量子金融系统的愿景、架构和逐步开发的技术文档。","ar":"وثيقة تقنية تصف رؤية وهيكل والتطوير التدريجي للنظام المالي الكمي.","th":"เอกสารทางเทคนิคที่อธิบายวิสัยทัศน์ สถาปัตยกรรม และการพัฒนาอย่างเป็นขั้นตอนของระบบการเงินควอนตัม"},
    "wp.sec01": {"en":"Executive Summary","es":"Resumen Ejecutivo","fr":"Résumé Exécutif","pt":"Resumo Executivo","de":"Zusammenfassung","zh":"执行摘要","ar":"الملخص التنفيذي","th":"บทสรุปผู้บริหาร"},
    "wp.sec02": {"en":"Vision & Architecture","es":"Visión y Arquitectura","fr":"Vision et Architecture","pt":"Visão e Arquitetura","de":"Vision und Architektur","zh":"愿景与架构","ar":"الرؤية والهيكل","th":"วิสัยทัศน์และสถาปัตยกรรม"},
    "wp.sec03": {"en":"Ecosystem Components","es":"Componentes del Ecosistema","fr":"Composants de l'Écosystème","pt":"Componentes do Ecossistema","de":"Ökosystem-Komponenten","zh":"生态系统组件","ar":"مكونات النظام","th":"ส่วนประกอบของระบบนิเวศ"},
    "wp.sec04": {"en":"Security & Cryptography","es":"Seguridad y Criptografía","fr":"Sécurité et Cryptographie","pt":"Segurança e Criptografia","de":"Sicherheit und Kryptografie","zh":"安全与加密术","ar":"الأمان والتشفير","th":"ความปลอดภัยและการเข้ารหัส"},
    "wp.sec05": {"en":"Multichain Infrastructure","es":"Infraestructura Multicadena","fr":"Infrastructure Multichaîne","pt":"Infraestrutura Multichain","de":"Multichain-Infrastruktur","zh":"多链基础设施","ar":"بنية تحتية متعددة السلسلة","th":"โครงสร้างพื้นฐานหลายเชน"},
    "wp.sec06": {"en":"Artificial Intelligence","es":"Inteligencia Artificial","fr":"Intelligence Artificielle","pt":"Inteligência Artificial","de":"Künstliche Intelligenz","zh":"人工智能","ar":"الذكاء الاصطناعي","th":"ปัญญาประดิษฐ์"},
    "wp.sec07": {"en":"Digital Asset Economy","es":"Economía de Activos Digitales","fr":"Économie des Actifs Numériques","pt":"Economia de Ativos Digitais","de":"Digitale Asset-Wirtschaft","zh":"数字资产经济","ar":"اقتصاد الأصول الرقمية","th":"เศรษฐกิจสินทรัพย์ดิจิทัล"},
    "wp.sec08": {"en":"Institutional Solutions","es":"Soluciones Institucionales","fr":"Solutions Institutionnelles","pt":"Soluções Institucionais","de":"Institutionelle Lösungen","zh":"机构解决方案","ar":"حلول مؤسسية","th":"โซลูชันสถาบัน"},
    "wp.sec09": {"en":"Strategic Alliances","es":"Alianzas Estratégicas","fr":"Alliances Stratégiques","pt":"Alianças Estratégicas","de":"Strategische Allianzen","zh":"战略联盟","ar":"التحالفات الاستراتيجية","th":"พันธมิตรเชิงกลยุทธ์"},
    "wp.sec10": {"en":"NESG Community","es":"Comunidad NESG","fr":"Communauté NESG","pt":"Comunidade NESG","de":"NESG-Community","zh":"NESG社区","ar":"مجتمع NESG","th":"ชุมชน NESG"},
    "wp.title": {"en":"QFS White Paper","es":"Libro Blanco QFS","fr":"Livre Blanc QFS","pt":"Livro Branco QFS","de":"QFS Whitepaper","zh":"QFS 白皮书","ar":"الوثيقة التفصيلية QFS","th":"เอกสารขาว QFS"},
    "wp.toc": {"en":"Contents","es":"Contenido","fr":"Contenu","pt":"Conteúdo","de":"Inhalt","zh":"目录","ar":"المحتويات","th":"สารบัญ"},
}

# All array translations (td)
td_keys = {
    "ai.items": {
        "en": ["AI Security", "Anomalous transaction detection", "AI Risk Monitoring", "Risk and pattern analysis", "AI Financial Assistance", "Smart tools for users", "AI Compliance", "Compliance automation"],
        "es": ["IA Seguridad", "Detección de transacciones anómalas", "IA Monitoreo de Riesgos", "Análisis de riesgos y patrones", "IA Asistencia Financiera", "Herramientas inteligentes", "IA Cumplimiento", "Automatización de cumplimiento"],
        "fr": ["IA Sécurité", "Détection de transactions anormales", "IA Surveillance des Risques", "Analyse des risques et patterns", "IA Assistance Financière", "Outils intelligents", "IA Conformité", "Automatisation de la conformité"],
        "pt": ["IA Segurança", "Detecção de transações anômalas", "IA Monitoramento de Riscos", "Análise de riscos e padrões", "IA Assistência Financeira", "Ferramentas inteligentes", "IA Conformidade", "Automação de conformidade"],
        "de": ["KI-Sicherheit", "Erkennung anomaler Transaktionen", "KI-Risikoüberwachung", "Risiko- und Musteranalyse", "KI-Finanzhilfe", "Intelligente Werkzeuge", "KI-Compliance", "Compliance-Automatisierung"],
        "zh": ["AI安全", "异常交易检测", "AI风险监控", "风险与模式分析", "AI金融助手", "智能工具", "AI合规", "合规自动化"],
        "ar": ["أمان الذكاء الاصطناعي", "كشف المعاملات غير الطبيعية", "مراقبة المخاطر بالذكاء الاصطناعي", "تحليل المخاطر والأنماط", "مساعدة مالية بالذكاء الاصطناعي", "أدوات ذكية للمستخدمين", "الامتثال بالذكاء الاصطناعي", "أتمتة الامتثال"],
        "th": ["AI ความปลอดภัย", "ตรวจจับธุรกรรมผิดปกติ", "AI ติดตามความเสี่ยง", "วิเคราะห์ความเสี่ยงและรูปแบบ", "AI ช่วยเหลือทางการเงิน", "เครื่องมืออัจฉริยะ", "AI ความสอดคล้อง", "ระบบปฏิบัติการความสอดคล้อง"],
    },
    "cards.flow": {
        "en": ["Wallet", "QFSPay", "Cards", "Payments"],
        "es": ["Wallet", "QFSPay", "Tarjetas", "Pagos"],
        "fr": ["Wallet", "QFSPay", "Cartes", "Paiements"],
        "pt": ["Wallet", "QFSPay", "Cartões", "Pagamentos"],
        "de": ["Wallet", "QFSPay", "Karten", "Zahlungen"],
        "zh": ["钱包", "QFSPay", "卡片", "支付"],
        "ar": ["محفظة", "QFSPay", "بطاقات", "الدفع"],
        "th": ["วอลเล็ต", "QFSPay", "บัตร", "การชำระเงิน"],
    },
    "dex.features": {
        "en": ["Asset swap", "Liquidity pools", "Multi-chain interoperability", "Market tools", "Smart contracts", "Decentralized governance"],
        "es": ["Swap de activos", "Pools de liquidez", "Interoperabilidad multicadena", "Herramientas de mercado", "Smart contracts", "Gobernanza descentralizada"],
        "fr": ["Échange d'actifs", "Pools de liquidité", "Interopérabilité multichaîne", "Outils de marché", "Contrats intelligents", "Gouvernance décentralisée"],
        "pt": ["Troca de ativos", "Pools de liquidez", "Interoperabilidade multichain", "Ferramentas de mercado", "Contratos inteligentes", "Governança descentralizada"],
        "de": ["Asset-Swap", "Liquiditätspools", "Multichain-Interoperabilität", "Marktwerkzeuge", "Smart Contracts", "Dezentrale Governance"],
        "zh": ["资产兑换", "流动性池", "多链互操作", "市场工具", "智能合约", "去中心化治理"],
        "ar": ["تبادل الأصول", "مجمعات السيولة", "تشابكية متعددة السلسلة", "أدوات السوق", "العقود الذكية", "الحكم اللامركزي"],
        "th": ["แลกเปลี่ยนสินทรัพย์", "สระสภาพคล่อง", "การทำงานร่วมกันหลายเชน", "เครื่องมือตลาด", "สมาร์ทคอนแทรกต์", "การกำกับดูแลแบบกระจายศูนย์"],
    },
    "eco.cards": {
        "en": ["QFS Core", "Technological infrastructure designed to connect the different components of the QFS ecosystem.", "QFSPay", "Digital payment system designed to facilitate payments, transfers and commercial operations.", "QFS Wallet", "Digital wallet to store, manage, receive and transfer digital assets securely.", "QFS Exchange DEX", "Decentralized platform for exchanging digital assets with ecosystem liquidity.", "QFS Quantum Cards", "QFS cards designed to connect digital assets with real-world payment solutions.", "QFS Financial Services", "Progressive integration of payments, exchange, asset management and enterprise solutions.", "QFS Global Network", "Interoperable infrastructure connecting users, enterprises, communities and blockchain networks.", "QFS AI", "Artificial intelligence layer for security, risk analysis and financial assistance."],
        "es": ["QFS Core", "Infraestructura tecnológica diseñada para conectar los diferentes componentes del ecosistema QFS.", "QFSPay", "Sistema de pago digital diseñado para facilitar pagos, transferencias y operaciones comerciales.", "QFS Wallet", "Billetera digital para almacenar, gestionar, recibir y transferir activos digitales de forma segura.", "QFS Exchange DEX", "Plataforma descentralizada para el intercambio de activos digitales con liquidez del ecosistema.", "QFS Quantum Cards", "Tarjetas QFS diseñadas para conectar activos digitales con soluciones de pago del mundo real.", "QFS Financial Services", "Integración progresiva de pagos, exchange, gestión de activos y soluciones empresariales.", "QFS Global Network", "Infraestructura interoperable que conecta usuarios, empresas, comunidades y redes blockchain.", "QFS AI", "Capa de inteligencia artificial para seguridad, análisis de riesgos y asistencia financiera."],
        "fr": ["QFS Core", "Infrastructure technologique conçue pour connecter les différents composants de l'écosystème QFS.", "QFSPay", "Système de paiement numérique conçu pour faciliter les paiements, les transferts et les opérations commerciales.", "QFS Wallet", "Portefeuille numérique pour stocker, gérer, recevoir et transférer des actifs numériques en toute sécurité.", "QFS Exchange DEX", "Plateforme décentralisée pour l'échange d'actifs numériques avec la liquidité de l'écosystème.", "QFS Quantum Cards", "Cartes QFS conçues pour connecter les actifs numériques aux solutions de paiement du monde réel.", "QFS Financial Services", "Intégration progressive des paiements, de l'échange, de la gestion d'actifs et des solutions d'entreprise.", "QFS Global Network", "Infrastructure interopérable connectant les utilisateurs, les entreprises, les communautés et les réseaux blockchain.", "QFS AI", "Couche d'intelligence artificielle pour la sécurité, l'analyse des risques et l'assistance financière."],
        "pt": ["QFS Core", "Infraestrutura tecnológica projetada para conectar os diferentes componentes do ecossistema QFS.", "QFSPay", "Sistema de pagamento digital projetado para facilitar pagamentos, transferências e operações comerciais.", "QFS Wallet", "Carteira digital para armazenar, gerenciar, receber e transferir ativos digitais com segurança.", "QFS Exchange DEX", "Plataforma descentralizada para troca de ativos digitais com liquidez do ecossistema.", "QFS Quantum Cards", "Cartões QFS projetados para conectar ativos digitais com soluções de pagamento do mundo real.", "QFS Financial Services", "Integração progressiva de pagamentos, exchange, gestão de ativos e soluções empresariais.", "QFS Global Network", "Infraestrutura interoperável conectando usuários, empresas, comunidades e redes blockchain.", "QFS AI", "Camada de inteligência artificial para segurança, análise de riscos e assistência financeira."],
        "de": ["QFS Core", "Technologische Infrastruktur zur Verbindung der verschiedenen Komponenten des QFS-Ökosystems.", "QFSPay", "Digitales Zahlungssystem zur Erleichterung von Zahlungen, Überweisungen und kommerziellen Operationen.", "QFS Wallet", "Digitale Wallet zur sicheren Speicherung, Verwaltung und Übertragung digitaler Assets.", "QFS Exchange DEX", "Dezentrale Plattform zum Austausch digitaler Assets mit Ökosystem-Liquidität.", "QFS Quantum Cards", "QFS-Karten zur Verbindung digitaler Assets mit realen Zahlungslösungen.", "QFS Financial Services", "Progressive Integration von Zahlungen, Börse, Asset-Management und Unternehmenslösungen.", "QFS Global Network", "Interoperable Infrastruktur zur Verbindung von Benutzern, Unternehmen, Communities und Blockchain-Netzwerken.", "QFS AI", "KI-Schicht für Sicherheit, Risikoanalyse und finanzielle Unterstützung."],
        "zh": ["QFS Core", "旨在连接QFS生态系统不同组件的技术基础设施。", "QFSPay", "旨在促进支付、转账和商业运营的数字支付系统。", "QFS Wallet", "用于安全存储、管理、接收和传输数字资产的数字钱包。", "QFS Exchange DEX", "具有生态系统流动性的去中心化数字资产交易平台。", "QFS Quantum Cards", "旨在将数字资产与现实世界支付解决方案连接的QFS卡。", "QFS Financial Services", "支付、交易、资产管理和企业解决方案的逐步整合。", "QFS Global Network", "连接用户、企业、社区和区块链网络的可互操作基础设施。", "QFS AI", "用于安全、风险分析和金融辅助的人工智能层。"],
        "ar": ["QFS Core", "بنية تحتية تقنية مصممة لربط مكونات نظام QFS المختلفة.", "QFSPay", "نظام دفع رقمي مصمم لتسهيل المدفوعات والتحويلات والعمليات التجارية.", "QFS Wallet", "محفظة رقمية لتخزين وإدارة واستلام وتحويل الأصول الرقمية بأمان.", "QFS Exchange DEX", "منصة لامركزية لتبادل الأصول الرقمية مع سيولة النظام.", "QFS Quantum Cards", "بطاقات QFS مصممة لربط الأصول الرقمية بحلول الدفع في العالم الحقيقي.", "QFS Financial Services", "التكامل التدريجي للمدفوعات والصرف وإدارة الأصول وحلول المؤسسات.", "QFS Global Network", "بنية تحتية قابلة للتشبيك تربط المستخدمين والمؤسسات والمجتمعات وشبكات البلوكتشين.", "QFS AI", "طبقة ذكاء اصطناعي للأمان وتحليل المخاطر والمساعدة المالية."],
        "th": ["QFS Core", "โครงสร้างพื้นฐานทางเทคโนโลยีที่ออกแบบมาเพื่อเชื่อมต่อส่วนประกอบต่างๆ ของระบบนิเวศ QFS", "QFSPay", "ระบบชำระเงินดิจิทัลที่ออกแบบมาเพื่ออำนวยความสะดวกในการชำระเงิน โอนเงิน และการดำเนินธุรกิจ", "QFS Wallet", "วอลเล็ตดิจิทัลสำหรับจัดเก็บ จัดการ รับ และโอนสินทรัพย์ดิจิทัลอย่างปลอดภัย", "QFS Exchange DEX", "แพลตฟอร์มแบบกระจายศูนย์สำหรับแลกเปลี่ยนสินทรัพย์ดิจิทัลกับสภาพคล่องของระบบนิเวศ", "QFS Quantum Cards", "บัตร QFS ที่ออกแบบมาเพื่อเชื่อมต่อสินทรัพย์ดิจิทัลกับโซลูชันการชำระเงินในโลกแห่งความเป็นจริง", "QFS Financial Services", "การผสานรวมอย่างเป็นขั้นตอนของการชำระเงิน การแลกเปลี่ยน การจัดการสินทรัพย์ และโซลูชันองค์กร", "QFS Global Network", "โครงสร้างพื้นฐานที่ทำงานร่วมกันได้ เชื่อมต่อผู้ใช้ องค์กร ชุมชน และเครือข่ายบล็อกเชน", "QFS AI", "ชั้นปัญญาประดิษฐ์สำหรับความปลอดภัย การวิเคราะห์ความเสี่ยง และการช่วยเหลือทางการเงิน"],
    },
    "faq.items": {
        "en": ["What is QFS?", "QFS Official is an initiative developing a digital financial services architecture and ecosystem inspired by technologies such as blockchain, advanced cryptography, artificial intelligence and interoperability. Its goal is to build an integrated infrastructure for the management, transfer and exchange of digital assets.", "Is QFS a global replacement for the banking system?", "No. QFS Official represents an initiative and technological vision in development. It should not be presented as an officially implemented global financial system or as a confirmed replacement for traditional banking. It is a proposal for complementary and evolutionary infrastructure.", "What is QFS Wallet?", "It is the digital wallet designed to manage assets and connect with the different services of the QFS ecosystem. It will allow users to create and manage wallets, send and receive digital assets, view balances, manage multiple networks and connect with QFSPay and QFS Exchange DEX.", "What is QFSPay?", "It is the digital payments infrastructure designed to connect users, merchants and financial services within the ecosystem. It will facilitate digital payments, transfers, peer-to-peer and commercial payments, asset conversion, and provide APIs for developers.", "What is QFS Exchange DEX?", "It is the decentralized component designed for exchanging digital assets. It will include asset swaps, liquidity pools, multi-chain interoperability, market tools, smart contracts and decentralized governance.", "What are QFS Quantum Cards?", "It is a development line designed to create cards connected with QFS Wallet and QFSPay. Subject to technological integration with payment providers and applicable regulation by jurisdiction. Its goal is to connect the digital ecosystem with real-world payment solutions.", "Is QFS connected to NESG?", "Yes. QFS Official is part of the technological and community vision developed around the NESG ecosystem, which drives initiatives related to digital finance, blockchain, DeFi, financial inclusion and technological innovation."],
        "es": ["¿Qué es QFS?", "QFS Official es una iniciativa que desarrolla una arquitectura y ecosistema de servicios financieros digitales inspirada en tecnologías como blockchain, criptografía avanzada, inteligencia artificial e interoperabilidad. Su objetivo es construir una infraestructura integrada para la gestión, transferencia e intercambio de activos digitales.", "¿Es QFS un reemplazo global del sistema bancario?", "No. QFS Official representa una iniciativa y visión tecnológica en desarrollo. No debe presentarse como un sistema financiero global implementado oficialmente ni como un reemplazo confirmado de la banca tradicional. Es una propuesta de infraestructura complementaria y evolutiva.", "¿Qué es QFS Wallet?", "Es la billetera digital diseñada para gestionar activos y conectarse con los diferentes servicios del ecosistema QFS. Permitirá a los usuarios crear y gestionar billeteras, enviar y recibir activos digitales, ver saldos, gestionar múltiples redes y conectarse con QFSPay y QFS Exchange DEX.", "¿Qué es QFSPay?", "Es la infraestructura de pagos digitales diseñada para conectar usuarios, comerciantes y servicios financieros dentro del ecosistema. Facilitará pagos digitales, transferencias, pagos P2P y comerciales, conversión de activos y proporcionará APIs para desarrolladores.", "¿Qué es QFS Exchange DEX?", "Es el componente descentralizado diseñado para el intercambio de activos digitales. Incluirá swaps de activos, pools de liquidez, interoperabilidad multicadena, herramientas de mercado, smart contracts y gobernanza descentralizada.", "¿Qué son las QFS Quantum Cards?", "Es una línea de desarrollo diseñada para crear tarjetas conectadas con QFS Wallet y QFSPay. Sujeta a integración tecnológica con proveedores de pago y regulación aplicable por jurisdicción. Su objetivo es conectar el ecosistema digital con soluciones de pago del mundo real.", "¿QFS está conectado a NESG?", "Sí. QFS Official es parte de la visión tecnológica y comunitaria desarrollada alrededor del ecosistema NESG, que impulsa iniciativas relacionadas con finanzas digitales, blockchain, DeFi, inclusión financiera e innovación tecnológica."],
        "fr": ["Qu'est-ce que QFS ?", "QFS Official est une initiative développant une architecture et un écosystème de services financiers numériques inspirés par des technologies telles que la blockchain, la cryptographie avancée, l'intelligence artificielle et l'interopérabilité. Son objectif est de construire une infrastructure intégrée pour la gestion, le transfert et l'échange d'actifs numériques.", "QFS est-il un remplacement mondial du système bancaire ?", "Non. QFS Official représente une initiative et une vision technologique en développement. Il ne doit pas être présenté comme un système financier mondial officiellement mis en œuvre ou comme un remplacement confirmé du système bancaire traditionnel. C'est une proposition d'infrastructure complémentaire et évolutive.", "Qu'est-ce que QFS Wallet ?", "C'est le portefeuille numérique conçu pour gérer les actifs et se connecter aux différents services de l'écosystème QFS. Il permettra aux utilisateurs de créer et gérer des portefeuilles, envoyer et recevoir des actifs numériques, consulter les soldes, gérer plusieurs réseaux et se connecter à QFSPay et QFS Exchange DEX.", "Qu'est-ce que QFSPay ?", "C'est l'infrastructure de paiements numériques conçue pour connecter les utilisateurs, les marchands et les services financiers au sein de l'écosystème. Elle facilitera les paiements numériques, les transferts, les paiements P2P et commerciaux, la conversion d'actifs et fournira des API pour les développeurs.", "Qu'est-ce que QFS Exchange DEX ?", "C'est le composant décentralisé conçu pour l'échange d'actifs numériques. Il inclura des échanges d'actifs, des pools de liquidité, l'interopérabilité multichaîne, des outils de marché, des contrats intelligents et une gouvernance décentralisée.", "Que sont les QFS Quantum Cards ?", "C'est une ligne de développement conçue pour créer des cartes connectées à QFS Wallet et QFSPay. Soumise à l'intégration technologique avec les fournisseurs de paiement et à la réglementation applicable par juridiction. Son objectif est de connecter l'écosystème numérique aux solutions de paiement du monde réel.", "QFS est-il connecté à NESG ?", "Oui. QFS Official fait partie de la vision technologique et communautaire développée autour de l'écosystème NESG, qui promeut des initiatives liées à la finance numérique, la blockchain, la DeFi, l'inclusion financière et l'innovation technologique."],
        "pt": ["O que é QFS?", "QFS Official é uma iniciativa que desenvolve uma arquitetura e ecossistema de serviços financeiros digitais inspirada em tecnologias como blockchain, criptografia avançada, inteligência artificial e interoperabilidade. Seu objetivo é construir uma infraestrutura integrada para a gestão, transferência e troca de ativos digitais.", "O QFS é um substituto global do sistema bancário?", "Não. QFS Official representa uma iniciativa e visão tecnológica em desenvolvimento. Não deve ser apresentado como um sistema financeiro global implementado oficialmente ou como um substituto confirmado do sistema bancário tradicional. É uma proposta de infraestrutura complementar e evolutiva.", "O que é QFS Wallet?", "É a carteira digital projetada para gerenciar ativos e se conectar aos diferentes serviços do ecossistema QFS. Permitirá que os usuários criem e gerenciem carteiras, enviem e recebam ativos digitais, visualizem saldos, gerenciem múltiplas redes e se conectem ao QFSPay e QFS Exchange DEX.", "O que é QFSPay?", "É a infraestrutura de pagamentos digitais projetada para conectar usuários, comerciantes e serviços financeiros dentro do ecossistema. Facilitará pagamentos digitais, transferências, pagamentos P2P e comerciais, conversão de ativos e fornecerá APIs para desenvolvedores.", "O que é QFS Exchange DEX?", "É o componente descentralizado projetado para troca de ativos digitais. Incluirá troca de ativos, pools de liquidez, interoperabilidade multichain, ferramentas de mercado, contratos inteligentes e governança descentralizada.", "O que são QFS Quantum Cards?", "É uma linha de desenvolvimento projetada para criar cartões conectados ao QFS Wallet e QFSPay. Sujeita à integração tecnológica com provedores de pagamento e regulamentação aplicável por jurisdição. Seu objetivo é conectar o ecossistema digital com soluções de pagamento do mundo real.", "O QFS está conectado ao NESG?", "Sim. QFS Official faz parte da visão tecnológica e comunitária desenvolvida em torno do ecossistema NESG, que impulsiona iniciativas relacionadas a finanças digitais, blockchain, DeFi, inclusão financeira e inovação tecnológica."],
        "de": ["Was ist QFS?", "QFS Official ist eine Initiative zur Entwicklung einer digitalen Finanzdienstleistungsarchitektur und eines Ökosystems, inspiriert von Technologien wie Blockchain, fortschrittliche Kryptografie, Künstliche Intelligenz und Interoperabilität. Das Ziel ist der Aufbau einer integrierten Infrastruktur für die Verwaltung, Übertragung und den Austausch digitaler Assets.", "Ist QFS ein globaler Ersatz des Bankensystems?", "Nein. QFS Official stellt eine Initiative und technologische Vision in der Entwicklung dar. Es sollte nicht als offiziell implementiertes globales Finanzsystem oder als bestätigter Ersatz für das traditionelle Bankensystem dargestellt werden. Es ist ein Vorschlag für eine komplementäre und evolutionäre Infrastruktur.", "Was ist QFS Wallet?", "Es ist die digitale Wallet, die entwickelt wurde, um Assets zu verwalten und sich mit den verschiedenen Diensten des QFS-Ökosystems zu verbinden. Sie ermöglicht es Benutzern, Wallets zu erstellen und zu verwalten, digitale Assets zu senden und zu empfangen, Guthaben anzuzeigen, mehrere Netzwerke zu verwalten und sich mit QFSPay und QFS Exchange DEX zu verbinden.", "Was ist QFSPay?", "Es ist die digitale Zahlungsinfrastruktur, die entwickelt wurde, um Benutzer, Händler und Finanzdienstleistungen innerhalb des Ökosystems zu verbinden. Sie erleichtert digitale Zahlungen, Überweisungen, P2P- und kommerzielle Zahlungen, Asset-Umwandlung und bietet APIs für Entwickler.", "Was ist QFS Exchange DEX?", "Es ist die dezentrale Komponente für den Austausch digitaler Assets. Sie umfasst Asset-Swaps, Liquiditätspools, Multichain-Interoperabilität, Marktwerkzeuge, Smart Contracts und dezentrale Governance.", "Was sind QFS Quantum Cards?", "Es ist eine Entwicklungslinie zur Erstellung von Karten, die mit QFS Wallet und QFSPay verbunden sind. Unterliegt der technologischen Integration mit Zahlungsanbietern und der geltenden Regulierung nach Gerichtsbarkeit. Das Ziel ist die Verbindung des digitalen Ökosystems mit realen Zahlungslösungen.", "Ist QFS mit NESG verbunden?", "Ja. QFS Official ist Teil der technologischen und gemeinschaftlichen Vision, die um das NESG-Ökosystem entwickelt wird, das Initiativen im Bereich digitale Finanzen, Blockchain, DeFi, finanzielle Inklusion und technologische Innovation vorantreibt."],
        "zh": ["什么是QFS？", "QFS Official是一项开发数字金融服务架构和生态系统的倡议，灵感来自区块链、高级加密、人工智能和互操作性等技术。其目标是构建一个集成基础设施，用于管理、传输和交换数字资产。", "QFS是全球银行系统的替代品吗？", "不是。QFS Official代表一项正在开发中的倡议和技术愿景。不应将其呈现为已正式实施的全球金融系统或传统银行的确认替代品。它是一项互补和进化性基础设施的提案。", "什么是QFS Wallet？", "它是旨在管理资产并连接QFS生态系统不同服务的数字钱包。它将允许用户创建和管理钱包、发送和接收数字资产、查看余额、管理多个网络，并与QFSPay和QFS Exchange DEX连接。", "什么是QFSPay？", "它是旨在连接生态系统内用户、商户和金融服务的数字支付基础设施。它将促进数字支付、转账、点对点和商业支付、资产兑换，并为开发者提供API。", "什么是QFS Exchange DEX？", "它是为交换数字资产而设计的去中心化组件。它将包括资产兑换、流动性池、多链互操作、市场工具、智能合约和去中心化治理。", "什么是QFS Quantum Cards？", "它是一条与QFS Wallet和QFSPay连接的卡片开发线。受限于与支付提供商的技术集成和适用的司法管辖区法规。其目标是将数字生态系统与现实世界的支付解决方案连接起来。", "QFS与NESG有关联吗？", "是的。QFS Official是围绕NESG生态系统开发的技术和社区愿景的一部分，该生态系统推动与数字金融、区块链、DeFi、金融包容性和技术创新相关的倡议。"],
        "ar": ["ما هو QFS؟", "QFS Official هي مبادرة تطور بنية و نظام خدمات مالية رقمية مستوحاة من تقنيات مثل البلوكتشين والتشفير المتقدم والذكاء الاصطناعي والتشابكية. هدفها بناء بنية تحتيا متكاملة لإدارة وتحويل وتبادل الأصول الرقمية.", "هل QFS بديل عالمي للنظام المصرفي؟", "لا. QFS Official يمثل مبادرة ورؤية تقنية قيد التطوير. لا ينبغي تقديمه كنظام مالي عالمي مطبق رسمياً أو كبديل مؤكد للنظام المصرفي التقليدي. إنه اقتراح لبنية تحتيا تكميلية تطورية.", "ما هي محفظة QFS؟", "هي المحفظة الرقمية المصممة لإدارة الأصول والتواصل مع الخدمات المختلفة لنظام QFS. ستسمح للمستخدمين بإنشاء وإدارة المحافظ وإرسال واستلام الأصول الرقمية وعرض الأرصدة وإدارة شبكات متعددة والتواصل مع QFSPay و QFS Exchange DEX.", "ما هو QFSPay؟", "هي بنية الدفع الرقمي المصممة لربط المستخدمين والتجار والخدمات المالية ضمن النظام. ستسهل المدفوعات الرقمية والتحويلات والمدفوعات النظير إلى نظير والتجارية وتحويل الأصول وتوفير واجهات برمجة للمطورين.", "ما هو QFS Exchange DEX؟", "هو المكون اللامركزي المصمم لتبادل الأصول الرقمية. سيشمل تبادل الأصول ومجمعات السيولة والتشابكية متعددة السلسلة وأدوات السوق والعقود الذكية والحكم اللامركزي.", "ما هي بطاقات QFS الكمية؟", "هي خط تطوير مصمم لإنشاء بطاقات متصلة بمحفظة QFS و QFSPay. تخضع للتكامل التكنولوجي مع مقدمي الدفع والأنظمة المعمول بها حسب الاختصاص القضائي. هدفها ربط النظام الرقمي بحلول الدفع في العالم الحقيقي.", "هل QFS متصل بـ NESG؟", "نعم. QFS Official جزء من الرؤية التقنية والمجتمعية المطورة حول نظام NESG الذي يدفع مبادرات تتعلق بالمال الرقمي والبلوكتشين والتمويل اللامركزي والشمول المالي والابتكار التقني."],
        "th": ["QFS คืออะไร?", "QFS Official เป็นโครงการที่พัฒนาสถาปัตยกรรมและระบบนิเวศบริการทางการเงินดิจิทัล โดยได้แรงบันดาลใจจากเทคโนโลยีเช่น บล็อกเชน การเข้ารหัสขั้นสูง ปัญญาประดิษฐ์ และการทำงานร่วมกัน โดยมีเป้าหมายเพื่อสร้างโครงสร้างพื้นฐานแบบบูรณาการสำหรับการจัดการ ส่งผ่าน และแลกเปลี่ยนสินทรัพย์ดิจิทัล", "QFS เป็นการแทนที่ระบบธนาคารทั่วโลกหรือไม่?", "ไม่ QFS Official เป็นโครงการและวิสัยทัศน์ทางเทคโนโลยีที่อยู่ระหว่างพัฒนา ไม่ควรนำเสนอว่าเป็นระบบการเงินระดับโลกที่ใช้งานอย่างเป็นทางการหรือเป็นการแทนที่ระบบธนาคารแบบดั้งเดิมที่ยืนยันแล้ว มันเป็นข้อเสนอสำหรับโครงสร้างพื้นฐานที่เสริมและมีวิวัฒนาการ", "QFS Wallet คืออะไร?", "เป็นวอลเล็ตดิจิทัลที่ออกแบบมาเพื่อจัดการสินทรัพย์และเชื่อมต่อกับบริการต่างๆ ของระบบนิเวศ QFS จะอนุญาตให้ผู้ใช้สร้างและจัดการวอลเล็ต ส่งและรับสินทรัพย์ดิจิทัล ดูยอดคงเหลือ จัดการหลายเครือข่าย และเชื่อมต่อกับ QFSPay และ QFS Exchange DEX", "QFSPay คืออะไร?", "เป็นโครงสร้างพื้นฐานการชำระเงินดิจิทัลที่ออกแบบมาเพื่อเชื่อมต่อผู้ใช้ พ่อค้า และบริการทางการเงินภายในระบบนิเวศ จะอำนวยความสะดวกในการชำระเงินดิจิทัล การโอนเงิน การชำระเงิน P2P และธุรกิจ การแลกเปลี่ยนสินทรัพย์ และจัดเตรียม API สำหรับนักพัฒนา", "QFS Exchange DEX คืออะไร?", "เป็นส่วนประกอบแบบกระจายศูนย์ที่ออกแบบมาสำหรับการแลกเปลี่ยนสินทรัพย์ดิจิทัล จะรวมการแลกเปลี่ยนสินทรัพย์ สระสภาพคล่อง การทำงานร่วมกันหลายเชน เครื่องมือตลาด สมาร์ทคอนแทรกต์ และการกำกับดูแลแบบกระจายศูนย์", "QFS Quantum Cards คืออะไร?", "เป็นสายการผลิตที่ออกแบบมาเพื่อสร้างบัตรที่เชื่อมต่อกับ QFS Wallet และ QFSPay ขึ้นอยู่กับการผสานรวมทางเทคโนโลยีกับผู้ให้บริการชำระเงินและข้อบังคับที่บังคับใช้ตามเขตอำนาจ โดยมีเป้าหมายเพื่อเชื่อมต่อระบบนิเวศดิจิทัลกับโซลูชันการชำระเงินในโลกแห่งความเป็นจริง", "QFS เชื่อมต่อกับ NESG หรือไม่?", "ใช่ QFS Official เป็นส่วนหนึ่งของวิสัยทัศน์ทางเทคโนโลยีและชุมชนที่พัฒนาขึ้นรอบๆ ระบบนิเวศ NESG ซึ่งขับเคลื่อนโครงการที่เกี่ยวข้องกับการเงินดิจิทัล บล็อกเชน DeFi การครอบคลุมทางการเงิน และนวัตกรรมทางเทคโนโลยี"],
    },
    "foot.alliances.list": {
        "en": ["GCRM Alliance", "Al Arab", "Government Currencies", "CBDCs", "Global Network"],
        "es": ["Alianza GCRM", "Al Arab", "Monedas de Gobiernos", "CBDCs", "Red Global"],
        "fr": ["Alliance GCRM", "Al Arab", "Monnaies Gouvernementales", "CBDCs", "Réseau Mondial"],
        "pt": ["Aliança GCRM", "Al Arab", "Moedas Governamentais", "CBDCs", "Rede Global"],
        "de": ["GCRM-Allianz", "Al Arab", "Regierungswährungen", "CBDCs", "Globales Netzwerk"],
        "zh": ["GCRM联盟", "Al Arab", "政府货币", "CBDCs", "全球网络"],
        "ar": ["تحالف GCRM", "Al Arab", "العملات الحكومية", "CBDCs", "الشبكة العالمية"],
        "th": ["พันธมิตร GCRM", "Al Arab", "สกุลเงินรัฐบาล", "CBDCs", "เครือข่ายระดับโลก"],
    },
    "foot.products.list": {
        "en": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "es": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "fr": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "pt": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "de": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "zh": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "ar": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
        "th": ["QFS Wallet", "QFSPay", "QFS Exchange DEX", "QFS Quantum Cards", "QFS AI"],
    },
    "foot.resources.list": {
        "en": ["White Paper", "Roadmap", "Technical Documentation", "APIs", "NESG Community"],
        "es": ["Libro Blanco", "Roadmap", "Documentación Técnica", "APIs", "Comunidad NESG"],
        "fr": ["Livre Blanc", "Feuille de Route", "Documentation Technique", "APIs", "Communauté NESG"],
        "pt": ["Livro Branco", "Roteiro", "Documentação Técnica", "APIs", "Comunidade NESG"],
        "de": ["Whitepaper", "Roadmap", "Technische Dokumentation", "APIs", "NESG-Community"],
        "zh": ["白皮书", "路线图", "技术文档", "APIs", "NESG社区"],
        "ar": ["الوثيقة التفصيلية", "خريطة الطريق", "التوثيق التقني", "APIs", "مجتمع NESG"],
        "th": ["เอกสารขาว", "แผนงาน", "เอกสารทางเทคนิค", "APIs", "ชุมชน NESG"],
    },
    "pil.items": {
        "en": ["Security", "Advanced protection of assets, accounts and financial operations.", "Transparency", "Verifiable records through distributed ledger technologies.", "Interoperability", "Connection between different networks, assets and financial systems.", "Decentralization", "Reduced dependency on traditional financial intermediaries.", "Innovation", "Blockchain, AI, advanced cryptography and emerging technologies."],
        "es": ["Seguridad", "Protección avanzada de activos, cuentas y operaciones financieras.", "Transparencia", "Registros verificables a través de tecnologías de registro distribuido.", "Interoperabilidad", "Conexión entre diferentes redes, activos y sistemas financieros.", "Descentralización", "Reducción de la dependencia de intermediarios financieros tradicionales.", "Innovación", "Blockchain, IA, criptografía avanzada y tecnologías emergentes."],
        "fr": ["Sécurité", "Protection avancée des actifs, comptes et opérations financières.", "Transparence", "Registres vérifiables grâce aux technologies de registre distribué.", "Interopérabilité", "Connexion entre différents réseaux, actifs et systèmes financiers.", "Décentralisation", "Réduction de la dépendance aux intermédiaires financiers traditionnels.", "Innovation", "Blockchain, IA, cryptographie avancée et technologies émergentes."],
        "pt": ["Segurança", "Proteção avançada de ativos, contas e operações financeiras.", "Transparência", "Registros verificáveis através de tecnologias de registro distribuído.", "Interoperabilidade", "Conexão entre diferentes redes, ativos e sistemas financeiros.", "Descentralização", "Redução da dependência de intermediários financeiros tradicionais.", "Inovação", "Blockchain, IA, criptografia avançada e tecnologias emergentes."],
        "de": ["Sicherheit", "Fortschrittlicher Schutz von Assets, Konten und Finanzoperationen.", "Transparenz", "Überprüfbare Aufzeichnungen durch Distributed-Ledger-Technologien.", "Interoperabilität", "Verbindung zwischen verschiedenen Netzwerken, Assets und Finanzsystemen.", "Dezentralisierung", "Reduzierte Abhängigkeit von traditionellen Finanzintermediären.", "Innovation", "Blockchain, KI, fortschrittliche Kryptografie und aufstrebende Technologien."],
        "zh": ["安全", "对资产、账户和金融操作的高级保护。", "透明度", "通过分布式账本技术的可验证记录。", "互操作性", "不同网络、资产和金融系统之间的连接。", "去中心化", "减少对传统金融中介的依赖。", "创新", "区块链、AI、高级加密和新兴技术。"],
        "ar": ["الأمان", "حماية متقدمة للأصول والحسابات والعمليات المالية.", "الشفافية", "سجلات قابلة للتحقق من خلال تقنيات الدفتر الموزع.", "التشابكية", "الترابط بين الشبكات والأصول والأنظمة المالية المختلفة.", "اللامركزية", "تقليل الاعتماد على الوسطاء الماليين التقليديين.", "الابتكار", "البلوكتشين والذكاء الاصطناعي والتشفير المتقدم والتقنيات الناشئة."],
        "th": ["ความปลอดภัย", "การป้องกันขั้นสูงของสินทรัพย์ บัญชี และการดำเนินงานทางการเงิน", "ความโปร่งใส", "บันทึกที่ตรวจสอบได้ผ่านเทคโนโลยีบัญชีแบบกระจายศูนย์", "การทำงานร่วมกัน", "การเชื่อมต่อระหว่างเครือข่าย สินทรัพย์ และระบบการเงินต่างๆ", "การกระจายอำนาจ", "ลดการพึ่งพาตัวกลางทางการเงินแบบดั้งเดิม", "นวัตกรรม", "บล็อกเชน AI การเข้ารหัสขั้นสูง และเทคโนโลยีที่กำลังเกิดใหม่"],
    },
    "qfspay.features": {
        "en": ["Digital payments", "P2P transfers", "Commercial payments", "Asset conversion", "Developer APIs", "Enterprise solutions"],
        "es": ["Pagos digitales", "Transferencias P2P", "Pagos comerciales", "Conversión de activos", "APIs para desarrolladores", "Soluciones empresariales"],
        "fr": ["Paiements numériques", "Transferts P2P", "Paiements commerciaux", "Conversion d'actifs", "APIs développeur", "Solutions d'entreprise"],
        "pt": ["Pagamentos digitais", "Transferências P2P", "Pagamentos comerciais", "Conversão de ativos", "APIs para desenvolvedores", "Soluções empresariais"],
        "de": ["Digitale Zahlungen", "P2P-Überweisungen", "Kommerzielle Zahlungen", "Asset-Umwandlung", "Entwickler-APIs", "Unternehmenslösungen"],
        "zh": ["数字支付", "P2P转账", "商业支付", "资产兑换", "开发者API", "企业解决方案"],
        "ar": ["الدفع الرقمي", "تحويلات P2P", "الدفع التجاري", "تحويل الأصول", "APIs للمطورين", "حلول مؤسسية"],
        "th": ["การชำระเงินดิจิทัล", "การโอน P2P", "การชำระเงินธุรกิจ", "การแลกเปลี่ยนสินทรัพย์", "API สำหรับนักพัฒนา", "โซลูชันองค์กร"],
    },
    "sec.features": {
        "en": ["Future-threat-resistant cryptography", "Multi-factor authentication", "Secure key management", "Real-time transaction monitoring", "Advanced wallet protection", "AI-powered anomaly detection", "Smart contract auditing", "Multi-layered security architecture", "Artificial intelligence applied to security"],
        "es": ["Criptografía resistente a amenazas futuras", "Autenticación multifactor", "Gestión segura de claves", "Monitoreo de transacciones en tiempo real", "Protección avanzada de wallet", "Detección de anomalías impulsada por IA", "Auditoría de smart contracts", "Arquitectura de seguridad multicapa", "Inteligencia artificial aplicada a la seguridad"],
        "fr": ["Cryptographie résistante aux menaces futures", "Authentification multifactorielle", "Gestion sécurisée des clés", "Surveillance des transactions en temps réel", "Protection avancée des portefeuilles", "Détection d'anomalies par IA", "Audit des contrats intelligents", "Architecture de sécurité multicouche", "Intelligence artificielle appliquée à la sécurité"],
        "pt": ["Criptografia resistente a ameaças futuras", "Autenticação multifator", "Gerenciamento seguro de chaves", "Monitoramento de transações em tempo real", "Proteção avançada de carteira", "Detecção de anomalias por IA", "Auditoria de contratos inteligentes", "Arquitetura de segurança multicamadas", "Inteligência artificial aplicada à segurança"],
        "de": ["Zukunftssicher Kryptografie", "Multi-Faktor-Authentifizierung", "Sichere Schlüsselverwaltung", "Echtzeit-Transaktionsüberwachung", "Fortgeschrittener Wallet-Schutz", "KI-gestützte Anomalieerkennung", "Smart-Contract-Auditierung", "Mehrschichtige Sicherheitsarchitektur", "Künstliche Intelligenz für Sicherheit"],
        "zh": ["抗未来威胁的加密技术", "多因素身份验证", "安全密钥管理", "实时交易监控", "高级钱包保护", "AI驱动的异常检测", "智能合约审计", "多层安全架构", "应用于安全的人工智能"],
        "ar": ["تشفير مقاوم للتهديدات المستقبلية", "مصادقة متعددة العوامل", "إدارة مفاتيح آمنة", "مراقبة المعاملات في الوقت الفعلي", "حماية متقدمة للمحفظة", "كشف الشذوذ بالذكاء الاصطناعي", "تدقيق العقود الذكية", "هيكل أماني متعدد الطبقات", "الذكاء الاصطناعي المطبق في الأمان"],
        "th": ["การเข้ารหัสที่ทนต่อภัยคุกคามในอนาคต", "การยืนยันตัวตนหลายปัจจัย", "การจัดการกุญแจอย่างปลอดภัย", "การติดตามธุรกรรมแบบเรียลไทม์", "การป้องกันวอลเล็ตขั้นสูง", "การตรวจจับความผิดปกติด้วย AI", "การตรวจสอบสมาร์ทคอนแทรกต์", "สถาปัตยกรรมความปลอดภัยหลายชั้น", "ปัญญาประดิษฐ์ประยุกต์ใช้กับความปลอดภัย"],
    },
    "token.alloc.labels": {
        "en": ["Global Humanitarian Fund", "Exchange & Liquidity Reserve", "QFS Technology & Ecosystem", "Global Adoption & Expansion", "Institutional & Stability Reserve", "Future Governance / Unallocated Reserve"],
        "es": ["Fondo Humanitario Global", "Reserva de Exchange y Liquidez", "Tecnología y Ecosistema QFS", "Adopción y Expansión Global", "Reserva Institucional y de Estabilidad", "Gobernanza Futura / Reserva No Asignada"],
        "fr": ["Fonds Humanitaire Mondial", "Réserve d'Exchange et de Liquidité", "Technologie et Écosystème QFS", "Adoption et Expansion Mondiale", "Réserve Institutionnelle et de Stabilité", "Gouvernance Future / Réserve Non Allouée"],
        "pt": ["Fundo Humanitário Global", "Reserva de Exchange e Liquidez", "Tecnologia e Ecossistema QFS", "Adoção e Expansão Global", "Reserva Institucional e de Estabilidade", "Governança Futura / Reserva Não Alocada"],
        "de": ["Globaler Humanitärer Fonds", "Exchange- und Liquiditätsreserve", "QFS Technologie und Ökosystem", "Globale Adoptions- und Expansion", "Institutionelle und Stabilitätsreserve", "Zukünfts-Governance / Nicht zugewiesene Reserve"],
        "zh": ["全球人道主义基金", "交易所与流动性储备", "QFS技术与生态系统", "全球采用与扩张", "机构与稳定储备", "未来治理/未分配储备"],
        "ar": ["صندوق الإغاثة الإنسانية العالمي", "احتياطي الصرف والسيولة", "تكنولوجيا ونظام QFS", "التبني والتوسع العالمي", "الاحتياطي المؤسسي والاستقرار", "الحوكمة المستقبلية / الاحتياطي غير المخصص"],
        "th": ["กองทุนมนุษยธรรมระดับโลก", "สำรอง Exchange และสภาพคล่อง", "เทคโนโลยีและระบบนิเวศ QFS", "การยอมรับและขยายตัวระดับโลก", "สำรองสถาบันและเสถียรภาพ", "การกำกับดูแลในอนาคต / สำรองที่ยังไม่จัดสรร"],
    },
    "wallet.features": {
        "en": ["Create and manage wallets", "Send and receive assets", "View balances", "Manage multiple networks", "Connect with QFSPay", "Integrate QFS Cards", "Transaction history", "Security management"],
        "es": ["Crear y gestionar billeteras", "Enviar y recibir activos", "Ver saldos", "Gestionar múltiples redes", "Conectar con QFSPay", "Integrar QFS Cards", "Historial de transacciones", "Gestión de seguridad"],
        "fr": ["Créer et gérer des portefeuilles", "Envoyer et recevoir des actifs", "Consulter les soldes", "Gérer plusieurs réseaux", "Se connecter à QFSPay", "Intégrer QFS Cards", "Historique des transactions", "Gestion de la sécurité"],
        "pt": ["Criar e gerenciar carteiras", "Enviar e receber ativos", "Visualizar saldos", "Gerenciar múltiplas redes", "Conectar com QFSPay", "Integrar QFS Cards", "Histórico de transações", "Gestão de segurança"],
        "de": ["Wallets erstellen und verwalten", "Assets senden und empfangen", "Guthaben anzeigen", "Mehrere Netzwerke verwalten", "Mit QFSPay verbinden", "QFS Cards integrieren", "Transaktionsverlauf", "Sicherheitsverwaltung"],
        "zh": ["创建和管理钱包", "发送和接收资产", "查看余额", "管理多个网络", "连接QFSPay", "集成QFS卡", "交易历史", "安全管理"],
        "ar": ["إنشاء وإدارة المحافظ", "إرسال واستلام الأصول", "عرض الأرصدة", "إدارة شبكات متعددة", "الاتصال بـ QFSPay", "دمج بطاقات QFS", "سجل المعاملات", "إدارة الأمان"],
        "th": ["สร้างและจัดการวอลเล็ต", "ส่งและรับสินทรัพย์", "ดูยอดคงเหลือ", "จัดการหลายเครือข่าย", "เชื่อมต่อกับ QFSPay", "ผสานรวม QFS Cards", "ประวัติธุรกรรม", "การจัดการความปลอดภัย"],
    },
}

# Generate lang-store.ts
lines = []
lines.append("import { create } from 'zustand';")
lines.append("import { persist } from 'zustand/middleware';")
lines.append("")
lines.append("type Lang = 'en' | 'es' | 'fr' | 'pt' | 'de' | 'zh' | 'ar' | 'th';")
lines.append("")
lines.append("interface LangStore {")
lines.append("  lang: Lang;")
lines.append("  setLang: (lang: Lang) => void;")
lines.append("}")
lines.append("")
lines.append("export const useLangStore = create<LangStore>()(")
lines.append("  persist(")
lines.append("    (set) => ({ lang: 'en', setLang: (lang) => set({ lang }) }),")
lines.append("    { name: 'qfs-lang' }")
lines.append("  )")
lines.append(");")
lines.append("")
lines.append("const t: Record<string, Record<Lang, string>> = {")

# Sort keys alphabetically
for key in sorted(t_keys.keys()):
    val = t_keys[key]
    lines.append(f'  "{key}": {{ {", ".join(f"{l}: {json.dumps(val.get(l, val["en"]))}" for l in LANGS)} }},')

lines.append("};")
lines.append("")
lines.append("const td: Record<string, Record<Lang, string[]>> = {")

for key in sorted(td_keys.keys()):
    val = td_keys[key]
    lines.append(f'  "{key}": {{')
    for l in LANGS:
        arr = val.get(l, val["en"])
        lines.append(f'    {l}: {json.dumps(arr, ensure_ascii=False)},')
    lines.append("  },")

lines.append("};")
lines.append("")
lines.append("export function useT() {")
lines.append("  const { lang } = useLangStore();")
lines.append("  return (key: string): string => t[key]?.[lang] ?? key;")
lines.append("}")
lines.append("")
lines.append("export function useTD() {")
lines.append("  const { lang } = useLangStore();")
lines.append("  return (key: string): string[] => td[key]?.[lang] ?? [];")
lines.append("}")

with open('/home/z/my-project/src/store/lang-store.ts', 'w') as f:
    f.write('\n'.join(lines))

print("lang-store.ts written successfully with", len(t_keys), "string keys and", len(td_keys), "array keys")
